//
//Argus 观枢 - HealthService 双向健康检查契约
//本文件定义 Gateway 与 Controller 之间的心跳与健康探测接口。
//MVP 阶段使用自定义空消息 ControllerHealthRequest，避免依赖 google.protobuf.Empty。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: argus/health.proto

package health

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ControllerHealthRequest 健康检查请求，MVP 阶段为空消息。
type ControllerHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControllerHealthRequest) Reset() {
	*x = ControllerHealthRequest{}
	mi := &file_argus_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerHealthRequest) ProtoMessage() {}

func (x *ControllerHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_argus_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerHealthRequest.ProtoReflect.Descriptor instead.
func (*ControllerHealthRequest) Descriptor() ([]byte, []int) {
	return file_argus_health_proto_rawDescGZIP(), []int{0}
}

// Heartbeat Gateway 上报的心跳载荷，含运行指标与计数器。
type Heartbeat struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	GatewayId         string                 `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	Timestamp         int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ActiveConnections int64                  `protobuf:"varint,3,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	RunningMode       string                 `protobuf:"bytes,4,opt,name=running_mode,json=runningMode,proto3" json:"running_mode,omitempty"`
	Counters          map[string]int64       `protobuf:"bytes,5,rep,name=counters,proto3" json:"counters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_argus_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_argus_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_argus_health_proto_rawDescGZIP(), []int{1}
}

func (x *Heartbeat) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *Heartbeat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Heartbeat) GetActiveConnections() int64 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *Heartbeat) GetRunningMode() string {
	if x != nil {
		return x.RunningMode
	}
	return ""
}

func (x *Heartbeat) GetCounters() map[string]int64 {
	if x != nil {
		return x.Counters
	}
	return nil
}

// HeartbeatAck Controller 对心跳的确认，可携带下行指令。
type HeartbeatAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReceivedAt    int64                  `protobuf:"varint,1,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	ControllerId  string                 `protobuf:"bytes,2,opt,name=controller_id,json=controllerId,proto3" json:"controller_id,omitempty"`
	Instruction   string                 `protobuf:"bytes,3,opt,name=instruction,proto3" json:"instruction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_argus_health_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_argus_health_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_argus_health_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatAck) GetReceivedAt() int64 {
	if x != nil {
		return x.ReceivedAt
	}
	return 0
}

func (x *HeartbeatAck) GetControllerId() string {
	if x != nil {
		return x.ControllerId
	}
	return ""
}

func (x *HeartbeatAck) GetInstruction() string {
	if x != nil {
		return x.Instruction
	}
	return ""
}

// HealthStatus Controller 健康状态报告。
type HealthStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       map[string]string      `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthStatus) Reset() {
	*x = HealthStatus{}
	mi := &file_argus_health_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthStatus) ProtoMessage() {}

func (x *HealthStatus) ProtoReflect() protoreflect.Message {
	mi := &file_argus_health_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthStatus.ProtoReflect.Descriptor instead.
func (*HealthStatus) Descriptor() ([]byte, []int) {
	return file_argus_health_proto_rawDescGZIP(), []int{3}
}

func (x *HealthStatus) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthStatus) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *HealthStatus) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_argus_health_proto protoreflect.FileDescriptor

const file_argus_health_proto_rawDesc = "" +
	"\n" +
	"\x12argus/health.proto\x12\x15argus.health.v1alpha1\"\x19\n" +
	"\x17ControllerHealthRequest\"\xa3\x02\n" +
	"\tHeartbeat\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x01 \x01(\tR\tgatewayId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12-\n" +
	"\x12active_connections\x18\x03 \x01(\x03R\x11activeConnections\x12!\n" +
	"\frunning_mode\x18\x04 \x01(\tR\vrunningMode\x12J\n" +
	"\bcounters\x18\x05 \x03(\v2..argus.health.v1alpha1.Heartbeat.CountersEntryR\bcounters\x1a;\n" +
	"\rCountersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"v\n" +
	"\fHeartbeatAck\x12\x1f\n" +
	"\vreceived_at\x18\x01 \x01(\x03R\n" +
	"receivedAt\x12#\n" +
	"\rcontroller_id\x18\x02 \x01(\tR\fcontrollerId\x12 \n" +
	"\vinstruction\x18\x03 \x01(\tR\vinstruction\"\xe8\x01\n" +
	"\fHealthStatus\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12J\n" +
	"\adetails\x18\x03 \x03(\v20.argus.health.v1alpha1.HealthStatus.DetailsEntryR\adetails\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xd5\x01\n" +
	"\rHealthService\x12[\n" +
	"\x10GatewayHeartbeat\x12 .argus.health.v1alpha1.Heartbeat\x1a#.argus.health.v1alpha1.HeartbeatAck(\x01\x12g\n" +
	"\x10ControllerHealth\x12..argus.health.v1alpha1.ControllerHealthRequest\x1a#.argus.health.v1alpha1.HealthStatusB?Z=github.com/ctkqiang/argus/pkg/pb/argus/health/v1alpha1;healthb\x06proto3"

var (
	file_argus_health_proto_rawDescOnce sync.Once
	file_argus_health_proto_rawDescData []byte
)

func file_argus_health_proto_rawDescGZIP() []byte {
	file_argus_health_proto_rawDescOnce.Do(func() {
		file_argus_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_argus_health_proto_rawDesc), len(file_argus_health_proto_rawDesc)))
	})
	return file_argus_health_proto_rawDescData
}

var file_argus_health_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_argus_health_proto_goTypes = []any{
	(*ControllerHealthRequest)(nil), // 0: argus.health.v1alpha1.ControllerHealthRequest
	(*Heartbeat)(nil),               // 1: argus.health.v1alpha1.Heartbeat
	(*HeartbeatAck)(nil),            // 2: argus.health.v1alpha1.HeartbeatAck
	(*HealthStatus)(nil),            // 3: argus.health.v1alpha1.HealthStatus
	nil,                             // 4: argus.health.v1alpha1.Heartbeat.CountersEntry
	nil,                             // 5: argus.health.v1alpha1.HealthStatus.DetailsEntry
}
var file_argus_health_proto_depIdxs = []int32{
	4, // 0: argus.health.v1alpha1.Heartbeat.counters:type_name -> argus.health.v1alpha1.Heartbeat.CountersEntry
	5, // 1: argus.health.v1alpha1.HealthStatus.details:type_name -> argus.health.v1alpha1.HealthStatus.DetailsEntry
	1, // 2: argus.health.v1alpha1.HealthService.GatewayHeartbeat:input_type -> argus.health.v1alpha1.Heartbeat
	0, // 3: argus.health.v1alpha1.HealthService.ControllerHealth:input_type -> argus.health.v1alpha1.ControllerHealthRequest
	2, // 4: argus.health.v1alpha1.HealthService.GatewayHeartbeat:output_type -> argus.health.v1alpha1.HeartbeatAck
	3, // 5: argus.health.v1alpha1.HealthService.ControllerHealth:output_type -> argus.health.v1alpha1.HealthStatus
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_argus_health_proto_init() }
func file_argus_health_proto_init() {
	if File_argus_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_argus_health_proto_rawDesc), len(file_argus_health_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_argus_health_proto_goTypes,
		DependencyIndexes: file_argus_health_proto_depIdxs,
		MessageInfos:      file_argus_health_proto_msgTypes,
	}.Build()
	File_argus_health_proto = out.File
	file_argus_health_proto_goTypes = nil
	file_argus_health_proto_depIdxs = nil
}
