//
//Argus 观枢 - HealthService 双向健康检查契约
//本文件定义 Gateway 与 Controller 之间的心跳与健康探测接口。
//MVP 阶段使用自定义空消息 ControllerHealthRequest，避免依赖 google.protobuf.Empty。

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: argus/health.proto

package health

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HealthService_GatewayHeartbeat_FullMethodName = "/argus.health.v1alpha1.HealthService/GatewayHeartbeat"
	HealthService_ControllerHealth_FullMethodName = "/argus.health.v1alpha1.HealthService/ControllerHealth"
)

// HealthServiceClient is the client API for HealthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HealthService 定义 Gateway 与 Controller 双向健康检查服务。
type HealthServiceClient interface {
	// GatewayHeartbeat Gateway 向 Controller 发送双向流式心跳。
	GatewayHeartbeat(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Heartbeat, HeartbeatAck], error)
	// ControllerHealth Gateway 主动探测 Controller 健康状态。
	ControllerHealth(ctx context.Context, in *ControllerHealthRequest, opts ...grpc.CallOption) (*HealthStatus, error)
}

type healthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHealthServiceClient(cc grpc.ClientConnInterface) HealthServiceClient {
	return &healthServiceClient{cc}
}

func (c *healthServiceClient) GatewayHeartbeat(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Heartbeat, HeartbeatAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HealthService_ServiceDesc.Streams[0], HealthService_GatewayHeartbeat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Heartbeat, HeartbeatAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HealthService_GatewayHeartbeatClient = grpc.ClientStreamingClient[Heartbeat, HeartbeatAck]

func (c *healthServiceClient) ControllerHealth(ctx context.Context, in *ControllerHealthRequest, opts ...grpc.CallOption) (*HealthStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthStatus)
	err := c.cc.Invoke(ctx, HealthService_ControllerHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HealthServiceServer is the server API for HealthService service.
// All implementations should embed UnimplementedHealthServiceServer
// for forward compatibility.
//
// HealthService 定义 Gateway 与 Controller 双向健康检查服务。
type HealthServiceServer interface {
	// GatewayHeartbeat Gateway 向 Controller 发送双向流式心跳。
	GatewayHeartbeat(grpc.ClientStreamingServer[Heartbeat, HeartbeatAck]) error
	// ControllerHealth Gateway 主动探测 Controller 健康状态。
	ControllerHealth(context.Context, *ControllerHealthRequest) (*HealthStatus, error)
}

// UnimplementedHealthServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHealthServiceServer struct{}

func (UnimplementedHealthServiceServer) GatewayHeartbeat(grpc.ClientStreamingServer[Heartbeat, HeartbeatAck]) error {
	return status.Error(codes.Unimplemented, "method GatewayHeartbeat not implemented")
}
func (UnimplementedHealthServiceServer) ControllerHealth(context.Context, *ControllerHealthRequest) (*HealthStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method ControllerHealth not implemented")
}
func (UnimplementedHealthServiceServer) testEmbeddedByValue() {}

// UnsafeHealthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HealthServiceServer will
// result in compilation errors.
type UnsafeHealthServiceServer interface {
	mustEmbedUnimplementedHealthServiceServer()
}

func RegisterHealthServiceServer(s grpc.ServiceRegistrar, srv HealthServiceServer) {
	// If the following call panics, it indicates UnimplementedHealthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HealthService_ServiceDesc, srv)
}

func _HealthService_GatewayHeartbeat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HealthServiceServer).GatewayHeartbeat(&grpc.GenericServerStream[Heartbeat, HeartbeatAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HealthService_GatewayHeartbeatServer = grpc.ClientStreamingServer[Heartbeat, HeartbeatAck]

func _HealthService_ControllerHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ControllerHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServiceServer).ControllerHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthService_ControllerHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServiceServer).ControllerHealth(ctx, req.(*ControllerHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HealthService_ServiceDesc is the grpc.ServiceDesc for HealthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HealthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "argus.health.v1alpha1.HealthService",
	HandlerType: (*HealthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ControllerHealth",
			Handler:    _HealthService_ControllerHealth_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GatewayHeartbeat",
			Handler:       _HealthService_GatewayHeartbeat_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "argus/health.proto",
}
