//
//Argus - EventService 事件上报契约
//
//一、字段编号承诺（生产零容忍违反）
//- AIEvent 字段编号 1..18 与 argus/v1alpha1 设计文档一一对应，永久锁定。
//- 新增字段一律从 22 起继续向后追加（19..21 已被 detection_results /
//risk_score / final_action 占用；reserved 22..500 防止被人插队抢占）。
//- 严禁：删字段、复用字号、改类型、改同名 repeated/singular。
//必须改的，废弃旧字段并在注释中写 deprecated=true，然后新建字段 +
//新编号 + 迁移期 N 个版本。
//
//二、投递与幂等语义
//- 事件上报 = Gateway 客户端流式批量推 → Controller 收完整批后 ACK。
//- 至少一次投递（at-least-once）：
// Controller 持久化层必须按 event_id 做唯一键 / 幂等 upsert。
// 同一批流里出现重复 event_id，Controller 去重后按 1 次计。
// Gateway 收到 failed_event_ids 后，原样（保留原 event_id）在下一条流里重试，
//严禁生成新的 event_id 重发（否则去重失效，storage 会双倍写）。
//- FinalAction / Severity 一律用 enum，别用 magic string；大小写、拼错一
//律会导致策略引擎 threshold 匹配失败。
//
//三、时间与时长语义
//- 所有绝对时间戳统一 google.protobuf.Timestamp（秒 + 纳秒），跨系统
//时区、闰秒、高精度埋点都统一处理；严禁再使用 int64 epoch ms 自己乘 1e6。
//- 所有重试间隔 / 超时 / 窗口时长统一 google.protobuf.Duration；
//严禁 ms 整数导致单位理解歧义和"+/- 1ms off-by-one"。

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: argus/event.proto

package event

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventService_ReportEvents_FullMethodName = "/argus.event.v1alpha1.EventService/ReportEvents"
)

// EventServiceClient is the client API for EventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EventService Gateway → Controller 的事件上报。
// 客户端半关闭流（CloseSend）之后，Controller 处理整批并返回一次 ReportAck。
type EventServiceClient interface {
	// ReportEvents 客户端流式批量上报审计事件；服务端对整批 ACK。
	// 禁止中途调用 WriteStatus 返回错误：流异常终止由客户端按 last_event_id
	// 与 failed_event_ids 做整批重放。
	ReportEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[AIEvent, ReportAck], error)
}

type eventServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEventServiceClient(cc grpc.ClientConnInterface) EventServiceClient {
	return &eventServiceClient{cc}
}

func (c *eventServiceClient) ReportEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[AIEvent, ReportAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EventService_ServiceDesc.Streams[0], EventService_ReportEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AIEvent, ReportAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventService_ReportEventsClient = grpc.ClientStreamingClient[AIEvent, ReportAck]

// EventServiceServer is the server API for EventService service.
// All implementations should embed UnimplementedEventServiceServer
// for forward compatibility.
//
// EventService Gateway → Controller 的事件上报。
// 客户端半关闭流（CloseSend）之后，Controller 处理整批并返回一次 ReportAck。
type EventServiceServer interface {
	// ReportEvents 客户端流式批量上报审计事件；服务端对整批 ACK。
	// 禁止中途调用 WriteStatus 返回错误：流异常终止由客户端按 last_event_id
	// 与 failed_event_ids 做整批重放。
	ReportEvents(grpc.ClientStreamingServer[AIEvent, ReportAck]) error
}

// UnimplementedEventServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventServiceServer struct{}

func (UnimplementedEventServiceServer) ReportEvents(grpc.ClientStreamingServer[AIEvent, ReportAck]) error {
	return status.Error(codes.Unimplemented, "method ReportEvents not implemented")
}
func (UnimplementedEventServiceServer) testEmbeddedByValue() {}

// UnsafeEventServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventServiceServer will
// result in compilation errors.
type UnsafeEventServiceServer interface {
	mustEmbedUnimplementedEventServiceServer()
}

func RegisterEventServiceServer(s grpc.ServiceRegistrar, srv EventServiceServer) {
	// If the following call panics, it indicates UnimplementedEventServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventService_ServiceDesc, srv)
}

func _EventService_ReportEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EventServiceServer).ReportEvents(&grpc.GenericServerStream[AIEvent, ReportAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventService_ReportEventsServer = grpc.ClientStreamingServer[AIEvent, ReportAck]

// EventService_ServiceDesc is the grpc.ServiceDesc for EventService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "argus.event.v1alpha1.EventService",
	HandlerType: (*EventServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReportEvents",
			Handler:       _EventService_ReportEvents_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "argus/event.proto",
}
