//
//Argus - EventService 事件上报契约
//
//一、字段编号承诺（生产零容忍违反）
//- AIEvent 字段编号 1..18 与 argus/v1alpha1 设计文档一一对应，永久锁定。
//- 新增字段一律从 22 起继续向后追加（19..21 已被 detection_results /
//risk_score / final_action 占用；reserved 22..500 防止被人插队抢占）。
//- 严禁：删字段、复用字号、改类型、改同名 repeated/singular。
//必须改的，废弃旧字段并在注释中写 deprecated=true，然后新建字段 +
//新编号 + 迁移期 N 个版本。
//
//二、投递与幂等语义
//- 事件上报 = Gateway 客户端流式批量推 → Controller 收完整批后 ACK。
//- 至少一次投递（at-least-once）：
// Controller 持久化层必须按 event_id 做唯一键 / 幂等 upsert。
// 同一批流里出现重复 event_id，Controller 去重后按 1 次计。
// Gateway 收到 failed_event_ids 后，原样（保留原 event_id）在下一条流里重试，
//严禁生成新的 event_id 重发（否则去重失效，storage 会双倍写）。
//- FinalAction / Severity 一律用 enum，别用 magic string；大小写、拼错一
//律会导致策略引擎 threshold 匹配失败。
//
//三、时间与时长语义
//- 所有绝对时间戳统一 google.protobuf.Timestamp（秒 + 纳秒），跨系统
//时区、闰秒、高精度埋点都统一处理；严禁再使用 int64 epoch ms 自己乘 1e6。
//- 所有重试间隔 / 超时 / 窗口时长统一 google.protobuf.Duration；
//严禁 ms 整数导致单位理解歧义和"+/- 1ms off-by-one"。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: argus/event.proto

package event

import (
	v1alpha1 "github.com/ctkqiang/argus/pkg/pb/argus/detection/v1alpha1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FinalAction 网关最后的放行/阻断决策。
// 一旦在 policy engine 里定好，网关必须严格执行（不能"没匹配就随便放"）。
// proto3 默认禁止 enum alias（同号多值），因此不写 allow_alias 就是"不允许"。
type FinalAction int32

const (
	// 未设置；gateway / controller 都要把 UNSPECIFIED 当非法输入处理
	// （要么 WARN+降级到 BLOCK，要么直接拒绝入库，看 policy.thresholds）。
	FinalAction_FINAL_ACTION_UNSPECIFIED FinalAction = 0
	// 无风险、放行。
	FinalAction_FINAL_ACTION_ALLOW FinalAction = 1
	// 有命中且超过阻断阈值、阻断请求。
	FinalAction_FINAL_ACTION_BLOCK FinalAction = 2
	// 检测器/策略引擎失败但系统判定降级放行（记录 failed_reason）。
	FinalAction_FINAL_ACTION_DEGRADED_ALLOW FinalAction = 3
	// 检测器/策略引擎失败但系统判定降级阻断（记录 failed_reason）。
	FinalAction_FINAL_ACTION_DEGRADED_BLOCK FinalAction = 4
)

// Enum value maps for FinalAction.
var (
	FinalAction_name = map[int32]string{
		0: "FINAL_ACTION_UNSPECIFIED",
		1: "FINAL_ACTION_ALLOW",
		2: "FINAL_ACTION_BLOCK",
		3: "FINAL_ACTION_DEGRADED_ALLOW",
		4: "FINAL_ACTION_DEGRADED_BLOCK",
	}
	FinalAction_value = map[string]int32{
		"FINAL_ACTION_UNSPECIFIED":    0,
		"FINAL_ACTION_ALLOW":          1,
		"FINAL_ACTION_BLOCK":          2,
		"FINAL_ACTION_DEGRADED_ALLOW": 3,
		"FINAL_ACTION_DEGRADED_BLOCK": 4,
	}
)

func (x FinalAction) Enum() *FinalAction {
	p := new(FinalAction)
	*p = x
	return p
}

func (x FinalAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FinalAction) Descriptor() protoreflect.EnumDescriptor {
	return file_argus_event_proto_enumTypes[0].Descriptor()
}

func (FinalAction) Type() protoreflect.EnumType {
	return &file_argus_event_proto_enumTypes[0]
}

func (x FinalAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FinalAction.Descriptor instead.
func (FinalAction) EnumDescriptor() ([]byte, []int) {
	return file_argus_event_proto_rawDescGZIP(), []int{0}
}

// Severity 事件整体严重度，与 policy.thresholds 的四段严格对齐。
// proto3 默认禁止 enum alias（同号多值），因此不写 allow_alias 就是"不允许"。
type Severity int32

const (
	// 未评级：gateway 要当异常处理（至少打 WARN 日志），别默认塞给用户。
	Severity_SEVERITY_UNSPECIFIED Severity = 0
	Severity_SEVERITY_LOW         Severity = 1 // 0.00 ≤ risk_score < 0.35
	Severity_SEVERITY_MEDIUM      Severity = 2 // 0.35 ≤ risk_score < 0.70
	Severity_SEVERITY_HIGH        Severity = 3 // 0.70 ≤ risk_score < 0.90
	Severity_SEVERITY_CRITICAL    Severity = 4 // 0.90 ≤ risk_score ≤ 1.00
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "SEVERITY_LOW",
		2: "SEVERITY_MEDIUM",
		3: "SEVERITY_HIGH",
		4: "SEVERITY_CRITICAL",
	}
	Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"SEVERITY_LOW":         1,
		"SEVERITY_MEDIUM":      2,
		"SEVERITY_HIGH":        3,
		"SEVERITY_CRITICAL":    4,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_argus_event_proto_enumTypes[1].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_argus_event_proto_enumTypes[1]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_argus_event_proto_rawDescGZIP(), []int{1}
}

// AIEvent 一条 LLM 出站请求对应的审计事件。
//
// 字段编号约定：
//
//	1-18  锁定（对应设计文档"AIEvent 字段基线 v1"）
//	19-21 现用（detection_results / risk_score / final_action）
//	22-500 reserved，新字段一律从 501 开始
type AIEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 1 事件全局唯一 ID。
	//   - 生成方：Gateway。建议 uuid v4。
	//   - 幂等：Controller 持久化层必须按 (cluster_id, event_id) 做唯一键。
	//   - 重试：重传时 event_id 必须与首次上报时完全相同（不准重新生成）。
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// 2 事件发生时间（Gateway 首次"看到请求/响应完成"的绝对时间）。
	//
	//	统一 google.protobuf.Timestamp（秒 + 纳秒），禁止用毫秒 epoch 自己换算。
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// 3 集群 ID。部署时通过 env / CRD 显式注入；MVP 不要自己从 apiserver
	//
	//	拉 namespace 哈希算"疑似 cluster id"，算不准会导致跨集群事件碰撞。
	ClusterId string `protobuf:"bytes,3,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	// 4 源 Pod 命名空间。为空字符串视为非法事件（gateway 自己过滤掉）。
	Namespace string `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// 5 源 Pod 名。
	PodName string `protobuf:"bytes,5,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	// 6 源 Pod 对应的上层工作负载（Deployment/StatefulSet/DaemonSet/...）名。
	//
	//	没解析到就空串（不要写 "unknown" 这种占位，空串语义更清晰）。
	Workload string `protobuf:"bytes,6,opt,name=workload,proto3" json:"workload,omitempty"`
	// 7 源容器名。MVP 如果只到 Pod 粒度就空串。
	Container string `protobuf:"bytes,7,opt,name=container,proto3" json:"container,omitempty"`
	// 8 五元组源 IP。一般是 PodIP；hostNetwork Pod 就是节点 IP。
	//
	//	存的是 IP 字符串（v4 dotted 或 v6 canonical），禁止前缀 /24 这种 CIDR。
	SourceIp string `protobuf:"bytes,8,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	// 9 请求目标。优先 SNI / Host header；拿不到就 IP:port。
	//
	//	不要把完整 URL（包含 path/query）塞进来，审计检索会炸。纯 host/ip:port。
	Destination string `protobuf:"bytes,9,opt,name=destination,proto3" json:"destination,omitempty"`
	// 10 匹配到的 LLMProvider 资源名（metadata.name）。
	//
	//	空串 = 没命中任何 LLMProvider；这时 provider_unknown 应写入 failure_reason。
	Provider string `protobuf:"bytes,10,opt,name=provider,proto3" json:"provider,omitempty"`
	// 11 模型 ID，比如 gpt-4o / anthropic.claude-v2。解析不到就空串。
	Model string `protobuf:"bytes,11,opt,name=model,proto3" json:"model,omitempty"`
	// 12 会话 ID。网关按 (namespace, pod, provider, model, 时间窗口) 聚出来的串 ID。
	//
	//	主要用于 detector 做会话历史拼接；没有会话概念可以空串。
	SessionId string `protobuf:"bytes,12,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// 13 请求 ID。优先复用上游 X-Request-Id；没有网关自己生成 uuid。
	//
	//	注意：这是"业务请求"的 ID，和事件 ID（event_id）不是一回事。
	RequestId string `protobuf:"bytes,13,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// 14 请求体截断 + 脱敏后的原文。默认 4KiB 上限；超长按 UTF-8 rune 截断，
	//
	//	严禁切在 surrogate / 多字节中间。敏感字段（token、密钥、PII）在此
	//	之前必须在 gateway 层做过脱敏替换，禁止原文打进事件。
	RequestPayload string `protobuf:"bytes,14,opt,name=request_payload,json=requestPayload,proto3" json:"request_payload,omitempty"`
	// 15 响应体截断 + 脱敏后的原文。默认 4KiB 上限；规则同 request_payload。
	ResponsePayload string `protobuf:"bytes,15,opt,name=response_payload,json=responsePayload,proto3" json:"response_payload,omitempty"`
	// 16 本事件的严重度分级，对齐 policy.thresholds 四段（详见 Severity 注释）。
	Severity Severity `protobuf:"varint,16,opt,name=severity,proto3,enum=argus.event.v1alpha1.Severity" json:"severity,omitempty"`
	// 17 request_payload 里的 prompt 文本（只取 user prompt，不包含 tools /
	//
	//	system）做的稳定哈希，用来做重复攻击聚类。
	//	推荐算法：sha256（hex 小写 64 字符）。没算就空串。
	PromptHash string `protobuf:"bytes,17,opt,name=prompt_hash,json=promptHash,proto3" json:"prompt_hash,omitempty"`
	// 18 如果本事件走了降级/失败，这里写原因码（稳定字符串，禁止带空格换行）：
	//
	//	  detector_timeout        检测器流水线超时
	//	  policy_unavailable      policy / thresholds 获取失败
	//	  tls_inspect_failed      TLS 握手中途失败 / ALPN 不支持 / MITM CA 不可信
	//	  provider_unknown        出站域名匹配不到 LLMProvider 资源
	//	  storage_backoff         上报方暂时过载，Controller 建议稍后重试
	//	没有任何失败就空串；有失败时 severity 也应同步升级（至少 MEDIUM）。
	FailureReason string `protobuf:"bytes,18,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	// 19 所有检测器结果。按 pipeline 顺序追加：rules → heuristic → encoding → semantic。
	//
	//	空列表 = 没跑任何检测器（常见于降级路径 + failure_reason=detector_timeout）。
	DetectionResults []*v1alpha1.DetectionResult `protobuf:"bytes,19,rep,name=detection_results,json=detectionResults,proto3" json:"detection_results,omitempty"`
	// 20 风险引擎最终打分，取值范围 [0.0, 1.0]。
	//   - 超界的 score 入库前必须按 max(min(x, 1), 0) 归一，并打 WARN 日志。
	//   - NaN / ±Inf 视为非法输入：controller 存为 0.0 + failure_reason=storage_backoff，
	//     让 gateway 下一批带该事件 ID 重放。
	RiskScore float64 `protobuf:"fixed64,20,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	// 21 网关最后决策。决定请求是否实际抵达 LLM provider，审计必须可追溯。
	FinalAction   FinalAction `protobuf:"varint,21,opt,name=final_action,json=finalAction,proto3,enum=argus.event.v1alpha1.FinalAction" json:"final_action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIEvent) Reset() {
	*x = AIEvent{}
	mi := &file_argus_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIEvent) ProtoMessage() {}

func (x *AIEvent) ProtoReflect() protoreflect.Message {
	mi := &file_argus_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIEvent.ProtoReflect.Descriptor instead.
func (*AIEvent) Descriptor() ([]byte, []int) {
	return file_argus_event_proto_rawDescGZIP(), []int{0}
}

func (x *AIEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *AIEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *AIEvent) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *AIEvent) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *AIEvent) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *AIEvent) GetWorkload() string {
	if x != nil {
		return x.Workload
	}
	return ""
}

func (x *AIEvent) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *AIEvent) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *AIEvent) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *AIEvent) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *AIEvent) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AIEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AIEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AIEvent) GetRequestPayload() string {
	if x != nil {
		return x.RequestPayload
	}
	return ""
}

func (x *AIEvent) GetResponsePayload() string {
	if x != nil {
		return x.ResponsePayload
	}
	return ""
}

func (x *AIEvent) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *AIEvent) GetPromptHash() string {
	if x != nil {
		return x.PromptHash
	}
	return ""
}

func (x *AIEvent) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

func (x *AIEvent) GetDetectionResults() []*v1alpha1.DetectionResult {
	if x != nil {
		return x.DetectionResults
	}
	return nil
}

func (x *AIEvent) GetRiskScore() float64 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *AIEvent) GetFinalAction() FinalAction {
	if x != nil {
		return x.FinalAction
	}
	return FinalAction_FINAL_ACTION_UNSPECIFIED
}

// ReportAck 控制器对一整批事件流的确认。
// 注意：返回值是"整批视角"的 ACK，不是"单条事件"的细粒度 ACK。
// 单条事件失败用 failed_event_ids 表达；gateway 负责重新组织下一条流。
type ReportAck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 1 本流实际收到的事件条数（= Controller 侧 stream.Recv() 成功的次数）。
	//
	//	用来帮助 gateway 排查"我发了 32 条但收到的只有 11 条"这种传输层面丢失。
	ReceivedEvents int64 `protobuf:"varint,1,opt,name=received_events,json=receivedEvents,proto3" json:"received_events,omitempty"`
	// 2 成功写到持久化介质（本地 PV / 对象存储 / 分析 DB）的条数。
	//
	//	注意：去重后才算"persist 成功"；重复事件不会让这个计数器累加。
	PersistedEvents int64 `protobuf:"varint,2,opt,name=persisted_events,json=persistedEvents,proto3" json:"persisted_events,omitempty"`
	// 3 本轮失败的 event_id 列表。Gateway 在下一条流里**原样重试这些事件**
	//
	//	（event_id 不能变；否则幂等会失效，storage 双倍写）。
	//	Controller 必须保证 failed_event_ids 中任意 ID 都没有被持久化。
	FailedEventIds []string `protobuf:"bytes,3,rep,name=failed_event_ids,json=failedEventIds,proto3" json:"failed_event_ids,omitempty"`
	// 4 本流最后一条成功持久化的 event_id。
	//
	//	Gateway 用来推进本地游标：比它更旧的事件可以放心丢掉。
	//	空串 = 本批一条都没成功持久化（gateway 应整批回滚重发）。
	LastEventId string `protobuf:"bytes,4,opt,name=last_event_id,json=lastEventId,proto3" json:"last_event_id,omitempty"`
	// 5 Controller 建议网关的重试间隔。默认 0 = 网关自己决定指数退避。
	//
	//	用 Duration，别再传毫秒 int 了（±1ms 问题和单位误解直接归零）。
	RetryDelay *durationpb.Duration `protobuf:"bytes,5,opt,name=retry_delay,json=retryDelay,proto3" json:"retry_delay,omitempty"`
	// 6 本批的处理窗口开始时间（controller 侧），0 = 没提供。
	WindowStart *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=window_start,json=windowStart,proto3" json:"window_start,omitempty"`
	// 7 本批的处理窗口结束时间（controller 侧），0 = 没提供。
	//
	//	gateway 据此判断 controller 是否还积压旧窗口，是否需要放慢上报速率。
	WindowEnd     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=window_end,json=windowEnd,proto3" json:"window_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportAck) Reset() {
	*x = ReportAck{}
	mi := &file_argus_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportAck) ProtoMessage() {}

func (x *ReportAck) ProtoReflect() protoreflect.Message {
	mi := &file_argus_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportAck.ProtoReflect.Descriptor instead.
func (*ReportAck) Descriptor() ([]byte, []int) {
	return file_argus_event_proto_rawDescGZIP(), []int{1}
}

func (x *ReportAck) GetReceivedEvents() int64 {
	if x != nil {
		return x.ReceivedEvents
	}
	return 0
}

func (x *ReportAck) GetPersistedEvents() int64 {
	if x != nil {
		return x.PersistedEvents
	}
	return 0
}

func (x *ReportAck) GetFailedEventIds() []string {
	if x != nil {
		return x.FailedEventIds
	}
	return nil
}

func (x *ReportAck) GetLastEventId() string {
	if x != nil {
		return x.LastEventId
	}
	return ""
}

func (x *ReportAck) GetRetryDelay() *durationpb.Duration {
	if x != nil {
		return x.RetryDelay
	}
	return nil
}

func (x *ReportAck) GetWindowStart() *timestamppb.Timestamp {
	if x != nil {
		return x.WindowStart
	}
	return nil
}

func (x *ReportAck) GetWindowEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.WindowEnd
	}
	return nil
}

var File_argus_event_proto protoreflect.FileDescriptor

const file_argus_event_proto_rawDesc = "" +
	"\n" +
	"\x11argus/event.proto\x12\x14argus.event.v1alpha1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x15argus/detection.proto\"\xbb\x06\n" +
	"\aAIEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x03 \x01(\tR\tclusterId\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12\x19\n" +
	"\bpod_name\x18\x05 \x01(\tR\apodName\x12\x1a\n" +
	"\bworkload\x18\x06 \x01(\tR\bworkload\x12\x1c\n" +
	"\tcontainer\x18\a \x01(\tR\tcontainer\x12\x1b\n" +
	"\tsource_ip\x18\b \x01(\tR\bsourceIp\x12 \n" +
	"\vdestination\x18\t \x01(\tR\vdestination\x12\x1a\n" +
	"\bprovider\x18\n" +
	" \x01(\tR\bprovider\x12\x14\n" +
	"\x05model\x18\v \x01(\tR\x05model\x12\x1d\n" +
	"\n" +
	"session_id\x18\f \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"request_id\x18\r \x01(\tR\trequestId\x12'\n" +
	"\x0frequest_payload\x18\x0e \x01(\tR\x0erequestPayload\x12)\n" +
	"\x10response_payload\x18\x0f \x01(\tR\x0fresponsePayload\x12:\n" +
	"\bseverity\x18\x10 \x01(\x0e2\x1e.argus.event.v1alpha1.SeverityR\bseverity\x12\x1f\n" +
	"\vprompt_hash\x18\x11 \x01(\tR\n" +
	"promptHash\x12%\n" +
	"\x0efailure_reason\x18\x12 \x01(\tR\rfailureReason\x12V\n" +
	"\x11detection_results\x18\x13 \x03(\v2).argus.detection.v1alpha1.DetectionResultR\x10detectionResults\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x14 \x01(\x01R\triskScore\x12D\n" +
	"\ffinal_action\x18\x15 \x01(\x0e2!.argus.event.v1alpha1.FinalActionR\vfinalActionJ\x05\b\x16\x10\xf5\x03\"\xe3\x02\n" +
	"\tReportAck\x12'\n" +
	"\x0freceived_events\x18\x01 \x01(\x03R\x0ereceivedEvents\x12)\n" +
	"\x10persisted_events\x18\x02 \x01(\x03R\x0fpersistedEvents\x12(\n" +
	"\x10failed_event_ids\x18\x03 \x03(\tR\x0efailedEventIds\x12\"\n" +
	"\rlast_event_id\x18\x04 \x01(\tR\vlastEventId\x12:\n" +
	"\vretry_delay\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\n" +
	"retryDelay\x12=\n" +
	"\fwindow_start\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vwindowStart\x129\n" +
	"\n" +
	"window_end\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\twindowEnd*\xa4\x01\n" +
	"\vFinalAction\x12\x1c\n" +
	"\x18FINAL_ACTION_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12FINAL_ACTION_ALLOW\x10\x01\x12\x16\n" +
	"\x12FINAL_ACTION_BLOCK\x10\x02\x12\x1f\n" +
	"\x1bFINAL_ACTION_DEGRADED_ALLOW\x10\x03\x12\x1f\n" +
	"\x1bFINAL_ACTION_DEGRADED_BLOCK\x10\x04\"\x05\bd\x10\xe7\a*|\n" +
	"\bSeverity\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fSEVERITY_LOW\x10\x01\x12\x13\n" +
	"\x0fSEVERITY_MEDIUM\x10\x02\x12\x11\n" +
	"\rSEVERITY_HIGH\x10\x03\x12\x15\n" +
	"\x11SEVERITY_CRITICAL\x10\x04\"\x05\bd\x10\xe7\a2`\n" +
	"\fEventService\x12P\n" +
	"\fReportEvents\x12\x1d.argus.event.v1alpha1.AIEvent\x1a\x1f.argus.event.v1alpha1.ReportAck(\x01B=Z;github.com/ctkqiang/argus/pkg/pb/argus/event/v1alpha1;eventb\x06proto3"

var (
	file_argus_event_proto_rawDescOnce sync.Once
	file_argus_event_proto_rawDescData []byte
)

func file_argus_event_proto_rawDescGZIP() []byte {
	file_argus_event_proto_rawDescOnce.Do(func() {
		file_argus_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_argus_event_proto_rawDesc), len(file_argus_event_proto_rawDesc)))
	})
	return file_argus_event_proto_rawDescData
}

var file_argus_event_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_argus_event_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_argus_event_proto_goTypes = []any{
	(FinalAction)(0),                 // 0: argus.event.v1alpha1.FinalAction
	(Severity)(0),                    // 1: argus.event.v1alpha1.Severity
	(*AIEvent)(nil),                  // 2: argus.event.v1alpha1.AIEvent
	(*ReportAck)(nil),                // 3: argus.event.v1alpha1.ReportAck
	(*timestamppb.Timestamp)(nil),    // 4: google.protobuf.Timestamp
	(*v1alpha1.DetectionResult)(nil), // 5: argus.detection.v1alpha1.DetectionResult
	(*durationpb.Duration)(nil),      // 6: google.protobuf.Duration
}
var file_argus_event_proto_depIdxs = []int32{
	4, // 0: argus.event.v1alpha1.AIEvent.timestamp:type_name -> google.protobuf.Timestamp
	1, // 1: argus.event.v1alpha1.AIEvent.severity:type_name -> argus.event.v1alpha1.Severity
	5, // 2: argus.event.v1alpha1.AIEvent.detection_results:type_name -> argus.detection.v1alpha1.DetectionResult
	0, // 3: argus.event.v1alpha1.AIEvent.final_action:type_name -> argus.event.v1alpha1.FinalAction
	6, // 4: argus.event.v1alpha1.ReportAck.retry_delay:type_name -> google.protobuf.Duration
	4, // 5: argus.event.v1alpha1.ReportAck.window_start:type_name -> google.protobuf.Timestamp
	4, // 6: argus.event.v1alpha1.ReportAck.window_end:type_name -> google.protobuf.Timestamp
	2, // 7: argus.event.v1alpha1.EventService.ReportEvents:input_type -> argus.event.v1alpha1.AIEvent
	3, // 8: argus.event.v1alpha1.EventService.ReportEvents:output_type -> argus.event.v1alpha1.ReportAck
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_argus_event_proto_init() }
func file_argus_event_proto_init() {
	if File_argus_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_argus_event_proto_rawDesc), len(file_argus_event_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_argus_event_proto_goTypes,
		DependencyIndexes: file_argus_event_proto_depIdxs,
		EnumInfos:         file_argus_event_proto_enumTypes,
		MessageInfos:      file_argus_event_proto_msgTypes,
	}.Build()
	File_argus_event_proto = out.File
	file_argus_event_proto_goTypes = nil
	file_argus_event_proto_depIdxs = nil
}
