//
//Argus - EventService 事件上报契约
//- AIEvent 字段编号 1-18 与设计文档一致，新增字段从 19 开始加。
//- 事件上报：Gateway 客户端流式批量推 → Controller 收完整批后 ACK。
//- 至少一次投递（at-least-once）：Controller 必须按 event_id 去重。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: argus/event.proto

package event

import (
	v1alpha1 "github.com/ctkqiang/argus/pkg/pb/argus/detection/v1alpha1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FinalAction 网关最后的放行/阻断决策。枚举比字符串稳，别乱拼大小写。
type FinalAction int32

const (
	FinalAction_FINAL_ACTION_UNSPECIFIED    FinalAction = 0
	FinalAction_FINAL_ACTION_ALLOW          FinalAction = 1
	FinalAction_FINAL_ACTION_BLOCK          FinalAction = 2
	FinalAction_FINAL_ACTION_DEGRADED_ALLOW FinalAction = 3
	FinalAction_FINAL_ACTION_DEGRADED_BLOCK FinalAction = 4
)

// Enum value maps for FinalAction.
var (
	FinalAction_name = map[int32]string{
		0: "FINAL_ACTION_UNSPECIFIED",
		1: "FINAL_ACTION_ALLOW",
		2: "FINAL_ACTION_BLOCK",
		3: "FINAL_ACTION_DEGRADED_ALLOW",
		4: "FINAL_ACTION_DEGRADED_BLOCK",
	}
	FinalAction_value = map[string]int32{
		"FINAL_ACTION_UNSPECIFIED":    0,
		"FINAL_ACTION_ALLOW":          1,
		"FINAL_ACTION_BLOCK":          2,
		"FINAL_ACTION_DEGRADED_ALLOW": 3,
		"FINAL_ACTION_DEGRADED_BLOCK": 4,
	}
)

func (x FinalAction) Enum() *FinalAction {
	p := new(FinalAction)
	*p = x
	return p
}

func (x FinalAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FinalAction) Descriptor() protoreflect.EnumDescriptor {
	return file_argus_event_proto_enumTypes[0].Descriptor()
}

func (FinalAction) Type() protoreflect.EnumType {
	return &file_argus_event_proto_enumTypes[0]
}

func (x FinalAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FinalAction.Descriptor instead.
func (FinalAction) EnumDescriptor() ([]byte, []int) {
	return file_argus_event_proto_rawDescGZIP(), []int{0}
}

// Severity 事件整体严重度，和 policy.thresholds 对齐。
type Severity int32

const (
	Severity_SEVERITY_UNSPECIFIED Severity = 0
	Severity_SEVERITY_LOW         Severity = 1
	Severity_SEVERITY_MEDIUM      Severity = 2
	Severity_SEVERITY_HIGH        Severity = 3
	Severity_SEVERITY_CRITICAL    Severity = 4
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "SEVERITY_LOW",
		2: "SEVERITY_MEDIUM",
		3: "SEVERITY_HIGH",
		4: "SEVERITY_CRITICAL",
	}
	Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"SEVERITY_LOW":         1,
		"SEVERITY_MEDIUM":      2,
		"SEVERITY_HIGH":        3,
		"SEVERITY_CRITICAL":    4,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_argus_event_proto_enumTypes[1].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_argus_event_proto_enumTypes[1]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_argus_event_proto_rawDescGZIP(), []int{1}
}

// AIEvent 一条 LLM 出站请求对应的审计事件。
// 1-18 编号锁定，以后要加新字段一律从 19 往后追加，不许插队。
type AIEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 1 事件全局唯一 ID。推荐 uuid v4。
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// 2 事件发生时间。epoch 毫秒。
	Timestamp int64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// 3 集群 ID。部署时通过 env/CRD 显式注入；MVP 别自己算 CA 哈希，算不准。
	ClusterId string `protobuf:"bytes,3,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	// 4 源 Pod 命名空间。
	Namespace string `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// 5 源 Pod 名。
	PodName string `protobuf:"bytes,5,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	// 6 源 Pod 对应的上层工作负载（Deployment/StatefulSet/DaemonSet...）名。
	Workload string `protobuf:"bytes,6,opt,name=workload,proto3" json:"workload,omitempty"`
	// 7 源容器名。MVP 没有就空串（粒度到 pod）。
	Container string `protobuf:"bytes,7,opt,name=container,proto3" json:"container,omitempty"`
	// 8 五元组源 IP。一般是 PodIP；hostNetwork 就是节点 IP。
	SourceIp string `protobuf:"bytes,8,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	// 9 请求目标。优先 SNI / Host，拿不到就 IP:port。
	Destination string `protobuf:"bytes,9,opt,name=destination,proto3" json:"destination,omitempty"`
	// 10 匹配到的 LLMProvider 资源名（metadata.name）。
	Provider string `protobuf:"bytes,10,opt,name=provider,proto3" json:"provider,omitempty"`
	// 11 模型 ID，比如 gpt-4o。解析不到空串。
	Model string `protobuf:"bytes,11,opt,name=model,proto3" json:"model,omitempty"`
	// 12 会话 ID。网关按 (namespace, pod, provider, model, 时间窗口) 聚出来的串 ID。
	SessionId string `protobuf:"bytes,12,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// 13 请求 ID。优先复用上游 X-Request-Id；没有网关自己生成 uuid。
	RequestId string `protobuf:"bytes,13,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// 14 请求体截断 + 脱敏后的原文。默认 4KiB 上限。
	RequestPayload string `protobuf:"bytes,14,opt,name=request_payload,json=requestPayload,proto3" json:"request_payload,omitempty"`
	// 15 响应体截断 + 脱敏后的原文。默认 4KiB 上限。
	ResponsePayload string `protobuf:"bytes,15,opt,name=response_payload,json=responsePayload,proto3" json:"response_payload,omitempty"`
	// 16 本事件的严重度分级，对齐 policy.thresholds。
	Severity Severity `protobuf:"varint,16,opt,name=severity,proto3,enum=argus.event.v1alpha1.Severity" json:"severity,omitempty"`
	// 17 request_payload 里的 prompt 文本（非 tools/system）做的稳定哈希，
	// 用来做重复攻击聚类。推荐 sha256（hex），没算就空串。
	PromptHash string `protobuf:"bytes,17,opt,name=prompt_hash,json=promptHash,proto3" json:"prompt_hash,omitempty"`
	// 18 如果本事件走了降级/失败，这里写原因码：detector_timeout /
	// policy_unavailable / tls_inspect_failed / provider_unknown。
	// 没有任何失败就空串。
	FailureReason string `protobuf:"bytes,18,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	// 19 所有检测器结果。按 pipeline 顺序追加（rules/heuristic/encoding/semantic）。
	DetectionResults []*v1alpha1.DetectionResult `protobuf:"bytes,19,rep,name=detection_results,json=detectionResults,proto3" json:"detection_results,omitempty"`
	// 20 风险引擎最终打分，范围 [0.0, 1.0]。
	RiskScore float64 `protobuf:"fixed64,20,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	// 21 网关最后决策。
	FinalAction   FinalAction `protobuf:"varint,21,opt,name=final_action,json=finalAction,proto3,enum=argus.event.v1alpha1.FinalAction" json:"final_action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIEvent) Reset() {
	*x = AIEvent{}
	mi := &file_argus_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIEvent) ProtoMessage() {}

func (x *AIEvent) ProtoReflect() protoreflect.Message {
	mi := &file_argus_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIEvent.ProtoReflect.Descriptor instead.
func (*AIEvent) Descriptor() ([]byte, []int) {
	return file_argus_event_proto_rawDescGZIP(), []int{0}
}

func (x *AIEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *AIEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AIEvent) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *AIEvent) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *AIEvent) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *AIEvent) GetWorkload() string {
	if x != nil {
		return x.Workload
	}
	return ""
}

func (x *AIEvent) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *AIEvent) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *AIEvent) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *AIEvent) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *AIEvent) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AIEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AIEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AIEvent) GetRequestPayload() string {
	if x != nil {
		return x.RequestPayload
	}
	return ""
}

func (x *AIEvent) GetResponsePayload() string {
	if x != nil {
		return x.ResponsePayload
	}
	return ""
}

func (x *AIEvent) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *AIEvent) GetPromptHash() string {
	if x != nil {
		return x.PromptHash
	}
	return ""
}

func (x *AIEvent) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

func (x *AIEvent) GetDetectionResults() []*v1alpha1.DetectionResult {
	if x != nil {
		return x.DetectionResults
	}
	return nil
}

func (x *AIEvent) GetRiskScore() float64 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *AIEvent) GetFinalAction() FinalAction {
	if x != nil {
		return x.FinalAction
	}
	return FinalAction_FINAL_ACTION_UNSPECIFIED
}

// ReportAck 控制器对一整批事件流的确认。
type ReportAck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 1 本流实际收到的事件条数。
	ReceivedEvents int64 `protobuf:"varint,1,opt,name=received_events,json=receivedEvents,proto3" json:"received_events,omitempty"`
	// 2 成功写到持久化介质（本地 PV / 对象存储）的条数。
	PersistedEvents int64 `protobuf:"varint,2,opt,name=persisted_events,json=persistedEvents,proto3" json:"persisted_events,omitempty"`
	// 3 本轮失败的 event_id 列表。网关在下一条流里原样重试这些事件。
	FailedEventIds []string `protobuf:"bytes,3,rep,name=failed_event_ids,json=failedEventIds,proto3" json:"failed_event_ids,omitempty"`
	// 4 本流最后一条成功持久化的 event_id。网关用来推进游标。
	LastEventId string `protobuf:"bytes,4,opt,name=last_event_id,json=lastEventId,proto3" json:"last_event_id,omitempty"`
	// 5 Controller 建议网关的重试间隔，毫秒。默认 0 = 网关自己决定退避。
	RetryDelayMs int64 `protobuf:"varint,5,opt,name=retry_delay_ms,json=retryDelayMs,proto3" json:"retry_delay_ms,omitempty"`
	// 6 本批的处理窗口开始时间（controller 侧），epoch 毫秒。0 代表没提供。
	WindowStartMs int64 `protobuf:"varint,6,opt,name=window_start_ms,json=windowStartMs,proto3" json:"window_start_ms,omitempty"`
	// 7 本批的处理窗口结束时间（controller 侧），epoch 毫秒。0 代表没提供。
	WindowEndMs   int64 `protobuf:"varint,7,opt,name=window_end_ms,json=windowEndMs,proto3" json:"window_end_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportAck) Reset() {
	*x = ReportAck{}
	mi := &file_argus_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportAck) ProtoMessage() {}

func (x *ReportAck) ProtoReflect() protoreflect.Message {
	mi := &file_argus_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportAck.ProtoReflect.Descriptor instead.
func (*ReportAck) Descriptor() ([]byte, []int) {
	return file_argus_event_proto_rawDescGZIP(), []int{1}
}

func (x *ReportAck) GetReceivedEvents() int64 {
	if x != nil {
		return x.ReceivedEvents
	}
	return 0
}

func (x *ReportAck) GetPersistedEvents() int64 {
	if x != nil {
		return x.PersistedEvents
	}
	return 0
}

func (x *ReportAck) GetFailedEventIds() []string {
	if x != nil {
		return x.FailedEventIds
	}
	return nil
}

func (x *ReportAck) GetLastEventId() string {
	if x != nil {
		return x.LastEventId
	}
	return ""
}

func (x *ReportAck) GetRetryDelayMs() int64 {
	if x != nil {
		return x.RetryDelayMs
	}
	return 0
}

func (x *ReportAck) GetWindowStartMs() int64 {
	if x != nil {
		return x.WindowStartMs
	}
	return 0
}

func (x *ReportAck) GetWindowEndMs() int64 {
	if x != nil {
		return x.WindowEndMs
	}
	return 0
}

var File_argus_event_proto protoreflect.FileDescriptor

const file_argus_event_proto_rawDesc = "" +
	"\n" +
	"\x11argus/event.proto\x12\x14argus.event.v1alpha1\x1a\x15argus/detection.proto\"\x98\x06\n" +
	"\aAIEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x03 \x01(\tR\tclusterId\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12\x19\n" +
	"\bpod_name\x18\x05 \x01(\tR\apodName\x12\x1a\n" +
	"\bworkload\x18\x06 \x01(\tR\bworkload\x12\x1c\n" +
	"\tcontainer\x18\a \x01(\tR\tcontainer\x12\x1b\n" +
	"\tsource_ip\x18\b \x01(\tR\bsourceIp\x12 \n" +
	"\vdestination\x18\t \x01(\tR\vdestination\x12\x1a\n" +
	"\bprovider\x18\n" +
	" \x01(\tR\bprovider\x12\x14\n" +
	"\x05model\x18\v \x01(\tR\x05model\x12\x1d\n" +
	"\n" +
	"session_id\x18\f \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"request_id\x18\r \x01(\tR\trequestId\x12'\n" +
	"\x0frequest_payload\x18\x0e \x01(\tR\x0erequestPayload\x12)\n" +
	"\x10response_payload\x18\x0f \x01(\tR\x0fresponsePayload\x12:\n" +
	"\bseverity\x18\x10 \x01(\x0e2\x1e.argus.event.v1alpha1.SeverityR\bseverity\x12\x1f\n" +
	"\vprompt_hash\x18\x11 \x01(\tR\n" +
	"promptHash\x12%\n" +
	"\x0efailure_reason\x18\x12 \x01(\tR\rfailureReason\x12V\n" +
	"\x11detection_results\x18\x13 \x03(\v2).argus.detection.v1alpha1.DetectionResultR\x10detectionResults\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x14 \x01(\x01R\triskScore\x12D\n" +
	"\ffinal_action\x18\x15 \x01(\x0e2!.argus.event.v1alpha1.FinalActionR\vfinalAction\"\x9f\x02\n" +
	"\tReportAck\x12'\n" +
	"\x0freceived_events\x18\x01 \x01(\x03R\x0ereceivedEvents\x12)\n" +
	"\x10persisted_events\x18\x02 \x01(\x03R\x0fpersistedEvents\x12(\n" +
	"\x10failed_event_ids\x18\x03 \x03(\tR\x0efailedEventIds\x12\"\n" +
	"\rlast_event_id\x18\x04 \x01(\tR\vlastEventId\x12$\n" +
	"\x0eretry_delay_ms\x18\x05 \x01(\x03R\fretryDelayMs\x12&\n" +
	"\x0fwindow_start_ms\x18\x06 \x01(\x03R\rwindowStartMs\x12\"\n" +
	"\rwindow_end_ms\x18\a \x01(\x03R\vwindowEndMs*\x9d\x01\n" +
	"\vFinalAction\x12\x1c\n" +
	"\x18FINAL_ACTION_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12FINAL_ACTION_ALLOW\x10\x01\x12\x16\n" +
	"\x12FINAL_ACTION_BLOCK\x10\x02\x12\x1f\n" +
	"\x1bFINAL_ACTION_DEGRADED_ALLOW\x10\x03\x12\x1f\n" +
	"\x1bFINAL_ACTION_DEGRADED_BLOCK\x10\x04*u\n" +
	"\bSeverity\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fSEVERITY_LOW\x10\x01\x12\x13\n" +
	"\x0fSEVERITY_MEDIUM\x10\x02\x12\x11\n" +
	"\rSEVERITY_HIGH\x10\x03\x12\x15\n" +
	"\x11SEVERITY_CRITICAL\x10\x042`\n" +
	"\fEventService\x12P\n" +
	"\fReportEvents\x12\x1d.argus.event.v1alpha1.AIEvent\x1a\x1f.argus.event.v1alpha1.ReportAck(\x01B=Z;github.com/ctkqiang/argus/pkg/pb/argus/event/v1alpha1;eventb\x06proto3"

var (
	file_argus_event_proto_rawDescOnce sync.Once
	file_argus_event_proto_rawDescData []byte
)

func file_argus_event_proto_rawDescGZIP() []byte {
	file_argus_event_proto_rawDescOnce.Do(func() {
		file_argus_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_argus_event_proto_rawDesc), len(file_argus_event_proto_rawDesc)))
	})
	return file_argus_event_proto_rawDescData
}

var file_argus_event_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_argus_event_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_argus_event_proto_goTypes = []any{
	(FinalAction)(0),                 // 0: argus.event.v1alpha1.FinalAction
	(Severity)(0),                    // 1: argus.event.v1alpha1.Severity
	(*AIEvent)(nil),                  // 2: argus.event.v1alpha1.AIEvent
	(*ReportAck)(nil),                // 3: argus.event.v1alpha1.ReportAck
	(*v1alpha1.DetectionResult)(nil), // 4: argus.detection.v1alpha1.DetectionResult
}
var file_argus_event_proto_depIdxs = []int32{
	1, // 0: argus.event.v1alpha1.AIEvent.severity:type_name -> argus.event.v1alpha1.Severity
	4, // 1: argus.event.v1alpha1.AIEvent.detection_results:type_name -> argus.detection.v1alpha1.DetectionResult
	0, // 2: argus.event.v1alpha1.AIEvent.final_action:type_name -> argus.event.v1alpha1.FinalAction
	2, // 3: argus.event.v1alpha1.EventService.ReportEvents:input_type -> argus.event.v1alpha1.AIEvent
	3, // 4: argus.event.v1alpha1.EventService.ReportEvents:output_type -> argus.event.v1alpha1.ReportAck
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_argus_event_proto_init() }
func file_argus_event_proto_init() {
	if File_argus_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_argus_event_proto_rawDesc), len(file_argus_event_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_argus_event_proto_goTypes,
		DependencyIndexes: file_argus_event_proto_depIdxs,
		EnumInfos:         file_argus_event_proto_enumTypes,
		MessageInfos:      file_argus_event_proto_msgTypes,
	}.Build()
	File_argus_event_proto = out.File
	file_argus_event_proto_goTypes = nil
	file_argus_event_proto_depIdxs = nil
}
