//
//Argus 观枢 - EventService 安全事件上报契约
//本文件定义标准化 AIEvent（Spec §14，字段编号严格 1-18 顺序保持一致）
//以及 Gateway 向 Controller 批量流式上报事件的服务接口。
//
//字段编号约定（禁止改动顺序或插入中间编号）：
//1-2  事件头：event_id、timestamp
//3-7  身份溯源：cluster_id、namespace、pod_name、workload、container
//8-9  网络流：source_ip、destination
//10-11 模型归属：provider、model
//12-13 会话追踪：session_id、request_id
//14-15 载荷：request_payload、response_payload（默认 4KiB 截断 + 脱敏）
//16-18 决策：detection_results、risk_score、final_action

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: argus/event.proto

package event

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventService_ReportEvents_FullMethodName = "/argus.event.v1alpha1.EventService/ReportEvents"
)

// EventServiceClient is the client API for EventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EventService 定义 Gateway 向 Controller 上报安全事件的服务。
//
// Gateway 端通过客户端流式一次性把一批 AIEvent 推送到 Controller，
// Controller 在整批写盘（或入队列）后返回一次 ReportAck，Gateway
// 据此更新本地游标与重试列表。事件语义遵循 at-least-once，
// Controller 端必须基于 event_id 做幂等写入。
type EventServiceClient interface {
	// ReportEvents 流式批量上报 AIEvent，Controller 返回单次批量确认。
	// 请求流：AIEvent（客户端写流，写完即 half-close）。
	// 响应：ReportAck（整批处理完成后返回一次）。
	ReportEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[AIEvent, ReportAck], error)
}

type eventServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEventServiceClient(cc grpc.ClientConnInterface) EventServiceClient {
	return &eventServiceClient{cc}
}

func (c *eventServiceClient) ReportEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[AIEvent, ReportAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EventService_ServiceDesc.Streams[0], EventService_ReportEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AIEvent, ReportAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventService_ReportEventsClient = grpc.ClientStreamingClient[AIEvent, ReportAck]

// EventServiceServer is the server API for EventService service.
// All implementations should embed UnimplementedEventServiceServer
// for forward compatibility.
//
// EventService 定义 Gateway 向 Controller 上报安全事件的服务。
//
// Gateway 端通过客户端流式一次性把一批 AIEvent 推送到 Controller，
// Controller 在整批写盘（或入队列）后返回一次 ReportAck，Gateway
// 据此更新本地游标与重试列表。事件语义遵循 at-least-once，
// Controller 端必须基于 event_id 做幂等写入。
type EventServiceServer interface {
	// ReportEvents 流式批量上报 AIEvent，Controller 返回单次批量确认。
	// 请求流：AIEvent（客户端写流，写完即 half-close）。
	// 响应：ReportAck（整批处理完成后返回一次）。
	ReportEvents(grpc.ClientStreamingServer[AIEvent, ReportAck]) error
}

// UnimplementedEventServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventServiceServer struct{}

func (UnimplementedEventServiceServer) ReportEvents(grpc.ClientStreamingServer[AIEvent, ReportAck]) error {
	return status.Error(codes.Unimplemented, "method ReportEvents not implemented")
}
func (UnimplementedEventServiceServer) testEmbeddedByValue() {}

// UnsafeEventServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventServiceServer will
// result in compilation errors.
type UnsafeEventServiceServer interface {
	mustEmbedUnimplementedEventServiceServer()
}

func RegisterEventServiceServer(s grpc.ServiceRegistrar, srv EventServiceServer) {
	// If the following call panics, it indicates UnimplementedEventServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventService_ServiceDesc, srv)
}

func _EventService_ReportEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EventServiceServer).ReportEvents(&grpc.GenericServerStream[AIEvent, ReportAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventService_ReportEventsServer = grpc.ClientStreamingServer[AIEvent, ReportAck]

// EventService_ServiceDesc is the grpc.ServiceDesc for EventService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "argus.event.v1alpha1.EventService",
	HandlerType: (*EventServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReportEvents",
			Handler:       _EventService_ReportEvents_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "argus/event.proto",
}
