// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: argus/event.proto

package event

import (
	v1alpha1 "github.com/ctkqiang/argus/pkg/pb/argus/detection/v1alpha1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FinalAction int32

const (
	FinalAction_FINAL_ACTION_UNSPECIFIED    FinalAction = 0
	FinalAction_FINAL_ACTION_ALLOW          FinalAction = 1
	FinalAction_FINAL_ACTION_BLOCK          FinalAction = 2
	FinalAction_FINAL_ACTION_DEGRADED_ALLOW FinalAction = 3
	FinalAction_FINAL_ACTION_DEGRADED_BLOCK FinalAction = 4
)

// Enum value maps for FinalAction.
var (
	FinalAction_name = map[int32]string{
		0: "FINAL_ACTION_UNSPECIFIED",
		1: "FINAL_ACTION_ALLOW",
		2: "FINAL_ACTION_BLOCK",
		3: "FINAL_ACTION_DEGRADED_ALLOW",
		4: "FINAL_ACTION_DEGRADED_BLOCK",
	}
	FinalAction_value = map[string]int32{
		"FINAL_ACTION_UNSPECIFIED":    0,
		"FINAL_ACTION_ALLOW":          1,
		"FINAL_ACTION_BLOCK":          2,
		"FINAL_ACTION_DEGRADED_ALLOW": 3,
		"FINAL_ACTION_DEGRADED_BLOCK": 4,
	}
)

func (x FinalAction) Enum() *FinalAction {
	p := new(FinalAction)
	*p = x
	return p
}

func (x FinalAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FinalAction) Descriptor() protoreflect.EnumDescriptor {
	return file_argus_event_proto_enumTypes[0].Descriptor()
}

func (FinalAction) Type() protoreflect.EnumType {
	return &file_argus_event_proto_enumTypes[0]
}

func (x FinalAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FinalAction.Descriptor instead.
func (FinalAction) EnumDescriptor() ([]byte, []int) {
	return file_argus_event_proto_rawDescGZIP(), []int{0}
}

type Severity int32

const (
	Severity_SEVERITY_UNSPECIFIED Severity = 0
	Severity_SEVERITY_LOW         Severity = 1
	Severity_SEVERITY_MEDIUM      Severity = 2
	Severity_SEVERITY_HIGH        Severity = 3
	Severity_SEVERITY_CRITICAL    Severity = 4
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "SEVERITY_LOW",
		2: "SEVERITY_MEDIUM",
		3: "SEVERITY_HIGH",
		4: "SEVERITY_CRITICAL",
	}
	Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"SEVERITY_LOW":         1,
		"SEVERITY_MEDIUM":      2,
		"SEVERITY_HIGH":        3,
		"SEVERITY_CRITICAL":    4,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_argus_event_proto_enumTypes[1].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_argus_event_proto_enumTypes[1]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_argus_event_proto_rawDescGZIP(), []int{1}
}

type AIEvent struct {
	state            protoimpl.MessageState      `protogen:"open.v1"`
	EventId          string                      `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Timestamp        *timestamppb.Timestamp      `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ClusterId        string                      `protobuf:"bytes,3,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Namespace        string                      `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	PodName          string                      `protobuf:"bytes,5,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	Workload         string                      `protobuf:"bytes,6,opt,name=workload,proto3" json:"workload,omitempty"`
	Container        string                      `protobuf:"bytes,7,opt,name=container,proto3" json:"container,omitempty"`
	SourceIp         string                      `protobuf:"bytes,8,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	Destination      string                      `protobuf:"bytes,9,opt,name=destination,proto3" json:"destination,omitempty"`
	Provider         string                      `protobuf:"bytes,10,opt,name=provider,proto3" json:"provider,omitempty"`
	Model            string                      `protobuf:"bytes,11,opt,name=model,proto3" json:"model,omitempty"`
	SessionId        string                      `protobuf:"bytes,12,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RequestId        string                      `protobuf:"bytes,13,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	RequestPayload   string                      `protobuf:"bytes,14,opt,name=request_payload,json=requestPayload,proto3" json:"request_payload,omitempty"`
	ResponsePayload  string                      `protobuf:"bytes,15,opt,name=response_payload,json=responsePayload,proto3" json:"response_payload,omitempty"`
	Severity         Severity                    `protobuf:"varint,16,opt,name=severity,proto3,enum=argus.event.v1alpha1.Severity" json:"severity,omitempty"`
	PromptHash       string                      `protobuf:"bytes,17,opt,name=prompt_hash,json=promptHash,proto3" json:"prompt_hash,omitempty"`
	FailureReason    string                      `protobuf:"bytes,18,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	DetectionResults []*v1alpha1.DetectionResult `protobuf:"bytes,19,rep,name=detection_results,json=detectionResults,proto3" json:"detection_results,omitempty"`
	RiskScore        float64                     `protobuf:"fixed64,20,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	FinalAction      FinalAction                 `protobuf:"varint,21,opt,name=final_action,json=finalAction,proto3,enum=argus.event.v1alpha1.FinalAction" json:"final_action,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AIEvent) Reset() {
	*x = AIEvent{}
	mi := &file_argus_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIEvent) ProtoMessage() {}

func (x *AIEvent) ProtoReflect() protoreflect.Message {
	mi := &file_argus_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIEvent.ProtoReflect.Descriptor instead.
func (*AIEvent) Descriptor() ([]byte, []int) {
	return file_argus_event_proto_rawDescGZIP(), []int{0}
}

func (x *AIEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *AIEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *AIEvent) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *AIEvent) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *AIEvent) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *AIEvent) GetWorkload() string {
	if x != nil {
		return x.Workload
	}
	return ""
}

func (x *AIEvent) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *AIEvent) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *AIEvent) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *AIEvent) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *AIEvent) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AIEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AIEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AIEvent) GetRequestPayload() string {
	if x != nil {
		return x.RequestPayload
	}
	return ""
}

func (x *AIEvent) GetResponsePayload() string {
	if x != nil {
		return x.ResponsePayload
	}
	return ""
}

func (x *AIEvent) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *AIEvent) GetPromptHash() string {
	if x != nil {
		return x.PromptHash
	}
	return ""
}

func (x *AIEvent) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

func (x *AIEvent) GetDetectionResults() []*v1alpha1.DetectionResult {
	if x != nil {
		return x.DetectionResults
	}
	return nil
}

func (x *AIEvent) GetRiskScore() float64 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *AIEvent) GetFinalAction() FinalAction {
	if x != nil {
		return x.FinalAction
	}
	return FinalAction_FINAL_ACTION_UNSPECIFIED
}

type ReportAck struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ReceivedEvents  int64                  `protobuf:"varint,1,opt,name=received_events,json=receivedEvents,proto3" json:"received_events,omitempty"`
	PersistedEvents int64                  `protobuf:"varint,2,opt,name=persisted_events,json=persistedEvents,proto3" json:"persisted_events,omitempty"`
	FailedEventIds  []string               `protobuf:"bytes,3,rep,name=failed_event_ids,json=failedEventIds,proto3" json:"failed_event_ids,omitempty"`
	LastEventId     string                 `protobuf:"bytes,4,opt,name=last_event_id,json=lastEventId,proto3" json:"last_event_id,omitempty"`
	RetryDelay      *durationpb.Duration   `protobuf:"bytes,5,opt,name=retry_delay,json=retryDelay,proto3" json:"retry_delay,omitempty"`
	WindowStart     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=window_start,json=windowStart,proto3" json:"window_start,omitempty"`
	WindowEnd       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=window_end,json=windowEnd,proto3" json:"window_end,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReportAck) Reset() {
	*x = ReportAck{}
	mi := &file_argus_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportAck) ProtoMessage() {}

func (x *ReportAck) ProtoReflect() protoreflect.Message {
	mi := &file_argus_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportAck.ProtoReflect.Descriptor instead.
func (*ReportAck) Descriptor() ([]byte, []int) {
	return file_argus_event_proto_rawDescGZIP(), []int{1}
}

func (x *ReportAck) GetReceivedEvents() int64 {
	if x != nil {
		return x.ReceivedEvents
	}
	return 0
}

func (x *ReportAck) GetPersistedEvents() int64 {
	if x != nil {
		return x.PersistedEvents
	}
	return 0
}

func (x *ReportAck) GetFailedEventIds() []string {
	if x != nil {
		return x.FailedEventIds
	}
	return nil
}

func (x *ReportAck) GetLastEventId() string {
	if x != nil {
		return x.LastEventId
	}
	return ""
}

func (x *ReportAck) GetRetryDelay() *durationpb.Duration {
	if x != nil {
		return x.RetryDelay
	}
	return nil
}

func (x *ReportAck) GetWindowStart() *timestamppb.Timestamp {
	if x != nil {
		return x.WindowStart
	}
	return nil
}

func (x *ReportAck) GetWindowEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.WindowEnd
	}
	return nil
}

var File_argus_event_proto protoreflect.FileDescriptor

const file_argus_event_proto_rawDesc = "" +
	"\n" +
	"\x11argus/event.proto\x12\x14argus.event.v1alpha1\x1a\x15argus/detection.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbb\x06\n" +
	"\aAIEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x03 \x01(\tR\tclusterId\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12\x19\n" +
	"\bpod_name\x18\x05 \x01(\tR\apodName\x12\x1a\n" +
	"\bworkload\x18\x06 \x01(\tR\bworkload\x12\x1c\n" +
	"\tcontainer\x18\a \x01(\tR\tcontainer\x12\x1b\n" +
	"\tsource_ip\x18\b \x01(\tR\bsourceIp\x12 \n" +
	"\vdestination\x18\t \x01(\tR\vdestination\x12\x1a\n" +
	"\bprovider\x18\n" +
	" \x01(\tR\bprovider\x12\x14\n" +
	"\x05model\x18\v \x01(\tR\x05model\x12\x1d\n" +
	"\n" +
	"session_id\x18\f \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"request_id\x18\r \x01(\tR\trequestId\x12'\n" +
	"\x0frequest_payload\x18\x0e \x01(\tR\x0erequestPayload\x12)\n" +
	"\x10response_payload\x18\x0f \x01(\tR\x0fresponsePayload\x12:\n" +
	"\bseverity\x18\x10 \x01(\x0e2\x1e.argus.event.v1alpha1.SeverityR\bseverity\x12\x1f\n" +
	"\vprompt_hash\x18\x11 \x01(\tR\n" +
	"promptHash\x12%\n" +
	"\x0efailure_reason\x18\x12 \x01(\tR\rfailureReason\x12V\n" +
	"\x11detection_results\x18\x13 \x03(\v2).argus.detection.v1alpha1.DetectionResultR\x10detectionResults\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x14 \x01(\x01R\triskScore\x12D\n" +
	"\ffinal_action\x18\x15 \x01(\x0e2!.argus.event.v1alpha1.FinalActionR\vfinalActionJ\x05\b\x16\x10\xf5\x03\"\xe3\x02\n" +
	"\tReportAck\x12'\n" +
	"\x0freceived_events\x18\x01 \x01(\x03R\x0ereceivedEvents\x12)\n" +
	"\x10persisted_events\x18\x02 \x01(\x03R\x0fpersistedEvents\x12(\n" +
	"\x10failed_event_ids\x18\x03 \x03(\tR\x0efailedEventIds\x12\"\n" +
	"\rlast_event_id\x18\x04 \x01(\tR\vlastEventId\x12:\n" +
	"\vretry_delay\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\n" +
	"retryDelay\x12=\n" +
	"\fwindow_start\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vwindowStart\x129\n" +
	"\n" +
	"window_end\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\twindowEnd*\xa4\x01\n" +
	"\vFinalAction\x12\x1c\n" +
	"\x18FINAL_ACTION_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12FINAL_ACTION_ALLOW\x10\x01\x12\x16\n" +
	"\x12FINAL_ACTION_BLOCK\x10\x02\x12\x1f\n" +
	"\x1bFINAL_ACTION_DEGRADED_ALLOW\x10\x03\x12\x1f\n" +
	"\x1bFINAL_ACTION_DEGRADED_BLOCK\x10\x04\"\x05\bd\x10\xe7\a*|\n" +
	"\bSeverity\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fSEVERITY_LOW\x10\x01\x12\x13\n" +
	"\x0fSEVERITY_MEDIUM\x10\x02\x12\x11\n" +
	"\rSEVERITY_HIGH\x10\x03\x12\x15\n" +
	"\x11SEVERITY_CRITICAL\x10\x04\"\x05\bd\x10\xe7\a2`\n" +
	"\fEventService\x12P\n" +
	"\fReportEvents\x12\x1d.argus.event.v1alpha1.AIEvent\x1a\x1f.argus.event.v1alpha1.ReportAck(\x01B=Z;github.com/ctkqiang/argus/pkg/pb/argus/event/v1alpha1;eventb\x06proto3"

var (
	file_argus_event_proto_rawDescOnce sync.Once
	file_argus_event_proto_rawDescData []byte
)

func file_argus_event_proto_rawDescGZIP() []byte {
	file_argus_event_proto_rawDescOnce.Do(func() {
		file_argus_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_argus_event_proto_rawDesc), len(file_argus_event_proto_rawDesc)))
	})
	return file_argus_event_proto_rawDescData
}

var file_argus_event_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_argus_event_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_argus_event_proto_goTypes = []any{
	(FinalAction)(0),                 // 0: argus.event.v1alpha1.FinalAction
	(Severity)(0),                    // 1: argus.event.v1alpha1.Severity
	(*AIEvent)(nil),                  // 2: argus.event.v1alpha1.AIEvent
	(*ReportAck)(nil),                // 3: argus.event.v1alpha1.ReportAck
	(*timestamppb.Timestamp)(nil),    // 4: google.protobuf.Timestamp
	(*v1alpha1.DetectionResult)(nil), // 5: argus.detection.v1alpha1.DetectionResult
	(*durationpb.Duration)(nil),      // 6: google.protobuf.Duration
}
var file_argus_event_proto_depIdxs = []int32{
	4, // 0: argus.event.v1alpha1.AIEvent.timestamp:type_name -> google.protobuf.Timestamp
	1, // 1: argus.event.v1alpha1.AIEvent.severity:type_name -> argus.event.v1alpha1.Severity
	5, // 2: argus.event.v1alpha1.AIEvent.detection_results:type_name -> argus.detection.v1alpha1.DetectionResult
	0, // 3: argus.event.v1alpha1.AIEvent.final_action:type_name -> argus.event.v1alpha1.FinalAction
	6, // 4: argus.event.v1alpha1.ReportAck.retry_delay:type_name -> google.protobuf.Duration
	4, // 5: argus.event.v1alpha1.ReportAck.window_start:type_name -> google.protobuf.Timestamp
	4, // 6: argus.event.v1alpha1.ReportAck.window_end:type_name -> google.protobuf.Timestamp
	2, // 7: argus.event.v1alpha1.EventService.ReportEvents:input_type -> argus.event.v1alpha1.AIEvent
	3, // 8: argus.event.v1alpha1.EventService.ReportEvents:output_type -> argus.event.v1alpha1.ReportAck
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_argus_event_proto_init() }
func file_argus_event_proto_init() {
	if File_argus_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_argus_event_proto_rawDesc), len(file_argus_event_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_argus_event_proto_goTypes,
		DependencyIndexes: file_argus_event_proto_depIdxs,
		EnumInfos:         file_argus_event_proto_enumTypes,
		MessageInfos:      file_argus_event_proto_msgTypes,
	}.Build()
	File_argus_event_proto = out.File
	file_argus_event_proto_goTypes = nil
	file_argus_event_proto_depIdxs = nil
}
