//
//Argus 观枢 - PodIdentityService Pod 身份溯源契约
//本文件定义 Gateway 通过源 IP:Port 查询集群内 Pod 身份元数据的服务。
//Controller 基于 conntrack + CNI 状态 + Kubernetes API 做身份映射。

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: argus/identity.proto

package identity

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PodIdentityService_Lookup_FullMethodName = "/argus.identity.v1alpha1.PodIdentityService/Lookup"
)

// PodIdentityServiceClient is the client API for PodIdentityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PodIdentityService 定义按源 IP 溯源 Pod 身份的查询服务。
type PodIdentityServiceClient interface {
	// Lookup 基于 (源 IP, 源端口, 时间戳) 查询对应的 Pod 身份元数据。
	Lookup(ctx context.Context, in *PodIdentityRequest, opts ...grpc.CallOption) (*PodIdentityResponse, error)
}

type podIdentityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPodIdentityServiceClient(cc grpc.ClientConnInterface) PodIdentityServiceClient {
	return &podIdentityServiceClient{cc}
}

func (c *podIdentityServiceClient) Lookup(ctx context.Context, in *PodIdentityRequest, opts ...grpc.CallOption) (*PodIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PodIdentityResponse)
	err := c.cc.Invoke(ctx, PodIdentityService_Lookup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PodIdentityServiceServer is the server API for PodIdentityService service.
// All implementations should embed UnimplementedPodIdentityServiceServer
// for forward compatibility.
//
// PodIdentityService 定义按源 IP 溯源 Pod 身份的查询服务。
type PodIdentityServiceServer interface {
	// Lookup 基于 (源 IP, 源端口, 时间戳) 查询对应的 Pod 身份元数据。
	Lookup(context.Context, *PodIdentityRequest) (*PodIdentityResponse, error)
}

// UnimplementedPodIdentityServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPodIdentityServiceServer struct{}

func (UnimplementedPodIdentityServiceServer) Lookup(context.Context, *PodIdentityRequest) (*PodIdentityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Lookup not implemented")
}
func (UnimplementedPodIdentityServiceServer) testEmbeddedByValue() {}

// UnsafePodIdentityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PodIdentityServiceServer will
// result in compilation errors.
type UnsafePodIdentityServiceServer interface {
	mustEmbedUnimplementedPodIdentityServiceServer()
}

func RegisterPodIdentityServiceServer(s grpc.ServiceRegistrar, srv PodIdentityServiceServer) {
	// If the following call panics, it indicates UnimplementedPodIdentityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PodIdentityService_ServiceDesc, srv)
}

func _PodIdentityService_Lookup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PodIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodIdentityServiceServer).Lookup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PodIdentityService_Lookup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodIdentityServiceServer).Lookup(ctx, req.(*PodIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PodIdentityService_ServiceDesc is the grpc.ServiceDesc for PodIdentityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PodIdentityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "argus.identity.v1alpha1.PodIdentityService",
	HandlerType: (*PodIdentityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Lookup",
			Handler:    _PodIdentityService_Lookup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "argus/identity.proto",
}
