//
//Argus 观枢 - PodIdentityService Pod 身份溯源契约
//本文件定义 Gateway 通过源 IP:Port 查询集群内 Pod 身份元数据的服务。
//Controller 基于 conntrack + CNI 状态 + Kubernetes API 做身份映射。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: argus/identity.proto

package identity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PodIdentityRequest Pod 身份查询请求。
type PodIdentityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceIp      string                 `protobuf:"bytes,1,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	SourcePort    int32                  `protobuf:"varint,2,opt,name=source_port,json=sourcePort,proto3" json:"source_port,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodIdentityRequest) Reset() {
	*x = PodIdentityRequest{}
	mi := &file_argus_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodIdentityRequest) ProtoMessage() {}

func (x *PodIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_argus_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodIdentityRequest.ProtoReflect.Descriptor instead.
func (*PodIdentityRequest) Descriptor() ([]byte, []int) {
	return file_argus_identity_proto_rawDescGZIP(), []int{0}
}

func (x *PodIdentityRequest) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *PodIdentityRequest) GetSourcePort() int32 {
	if x != nil {
		return x.SourcePort
	}
	return 0
}

func (x *PodIdentityRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// PodIdentityResponse Pod 身份查询响应，含命名空间、工作负载等元数据。
type PodIdentityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	PodName       string                 `protobuf:"bytes,3,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	Workload      string                 `protobuf:"bytes,4,opt,name=workload,proto3" json:"workload,omitempty"`
	WorkloadKind  string                 `protobuf:"bytes,5,opt,name=workload_kind,json=workloadKind,proto3" json:"workload_kind,omitempty"`
	Container     string                 `protobuf:"bytes,6,opt,name=container,proto3" json:"container,omitempty"`
	HostNetwork   string                 `protobuf:"bytes,7,opt,name=host_network,json=hostNetwork,proto3" json:"host_network,omitempty"`
	CacheHit      int64                  `protobuf:"varint,8,opt,name=cache_hit,json=cacheHit,proto3" json:"cache_hit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodIdentityResponse) Reset() {
	*x = PodIdentityResponse{}
	mi := &file_argus_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodIdentityResponse) ProtoMessage() {}

func (x *PodIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_argus_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodIdentityResponse.ProtoReflect.Descriptor instead.
func (*PodIdentityResponse) Descriptor() ([]byte, []int) {
	return file_argus_identity_proto_rawDescGZIP(), []int{1}
}

func (x *PodIdentityResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *PodIdentityResponse) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PodIdentityResponse) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *PodIdentityResponse) GetWorkload() string {
	if x != nil {
		return x.Workload
	}
	return ""
}

func (x *PodIdentityResponse) GetWorkloadKind() string {
	if x != nil {
		return x.WorkloadKind
	}
	return ""
}

func (x *PodIdentityResponse) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *PodIdentityResponse) GetHostNetwork() string {
	if x != nil {
		return x.HostNetwork
	}
	return ""
}

func (x *PodIdentityResponse) GetCacheHit() int64 {
	if x != nil {
		return x.CacheHit
	}
	return 0
}

var File_argus_identity_proto protoreflect.FileDescriptor

const file_argus_identity_proto_rawDesc = "" +
	"\n" +
	"\x14argus/identity.proto\x12\x17argus.identity.v1alpha1\"p\n" +
	"\x12PodIdentityRequest\x12\x1b\n" +
	"\tsource_ip\x18\x01 \x01(\tR\bsourceIp\x12\x1f\n" +
	"\vsource_port\x18\x02 \x01(\x05R\n" +
	"sourcePort\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"\x83\x02\n" +
	"\x13PodIdentityResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x19\n" +
	"\bpod_name\x18\x03 \x01(\tR\apodName\x12\x1a\n" +
	"\bworkload\x18\x04 \x01(\tR\bworkload\x12#\n" +
	"\rworkload_kind\x18\x05 \x01(\tR\fworkloadKind\x12\x1c\n" +
	"\tcontainer\x18\x06 \x01(\tR\tcontainer\x12!\n" +
	"\fhost_network\x18\a \x01(\tR\vhostNetwork\x12\x1b\n" +
	"\tcache_hit\x18\b \x01(\x03R\bcacheHit2y\n" +
	"\x12PodIdentityService\x12c\n" +
	"\x06Lookup\x12+.argus.identity.v1alpha1.PodIdentityRequest\x1a,.argus.identity.v1alpha1.PodIdentityResponseBCZAgithub.com/ctkqiang/argus/pkg/pb/argus/identity/v1alpha1;identityb\x06proto3"

var (
	file_argus_identity_proto_rawDescOnce sync.Once
	file_argus_identity_proto_rawDescData []byte
)

func file_argus_identity_proto_rawDescGZIP() []byte {
	file_argus_identity_proto_rawDescOnce.Do(func() {
		file_argus_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_argus_identity_proto_rawDesc), len(file_argus_identity_proto_rawDesc)))
	})
	return file_argus_identity_proto_rawDescData
}

var file_argus_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_argus_identity_proto_goTypes = []any{
	(*PodIdentityRequest)(nil),  // 0: argus.identity.v1alpha1.PodIdentityRequest
	(*PodIdentityResponse)(nil), // 1: argus.identity.v1alpha1.PodIdentityResponse
}
var file_argus_identity_proto_depIdxs = []int32{
	0, // 0: argus.identity.v1alpha1.PodIdentityService.Lookup:input_type -> argus.identity.v1alpha1.PodIdentityRequest
	1, // 1: argus.identity.v1alpha1.PodIdentityService.Lookup:output_type -> argus.identity.v1alpha1.PodIdentityResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_argus_identity_proto_init() }
func file_argus_identity_proto_init() {
	if File_argus_identity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_argus_identity_proto_rawDesc), len(file_argus_identity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_argus_identity_proto_goTypes,
		DependencyIndexes: file_argus_identity_proto_depIdxs,
		MessageInfos:      file_argus_identity_proto_msgTypes,
	}.Build()
	File_argus_identity_proto = out.File
	file_argus_identity_proto_goTypes = nil
	file_argus_identity_proto_depIdxs = nil
}
