//
//Argus 观枢 - PolicyService 策略下发契约
//本文件定义 Controller 向 Gateway 下发 ArgusSecurityPolicy 和 LLMProvider
//配置的双向流式 gRPC 服务。Gateway 发起 watch，Controller 推送全量+增量快照。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: argus/policy.proto

package policy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WatchRequest Gateway 向 Controller 发起的 watch 请求，携带本地已知版本。
type WatchRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GatewayId        string                 `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	LastKnownVersion string                 `protobuf:"bytes,2,opt,name=last_known_version,json=lastKnownVersion,proto3" json:"last_known_version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_argus_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_argus_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_argus_policy_proto_rawDescGZIP(), []int{0}
}

func (x *WatchRequest) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *WatchRequest) GetLastKnownVersion() string {
	if x != nil {
		return x.LastKnownVersion
	}
	return ""
}

// PolicySnapshot Controller 下发的 ArgusSecurityPolicy 策略快照。
type PolicySnapshot struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Version       int64                      `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Items         []*ArgusSecurityPolicyItem `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	FullSnapshot  bool                       `protobuf:"varint,3,opt,name=full_snapshot,json=fullSnapshot,proto3" json:"full_snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicySnapshot) Reset() {
	*x = PolicySnapshot{}
	mi := &file_argus_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicySnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicySnapshot) ProtoMessage() {}

func (x *PolicySnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_argus_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicySnapshot.ProtoReflect.Descriptor instead.
func (*PolicySnapshot) Descriptor() ([]byte, []int) {
	return file_argus_policy_proto_rawDescGZIP(), []int{1}
}

func (x *PolicySnapshot) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PolicySnapshot) GetItems() []*ArgusSecurityPolicyItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *PolicySnapshot) GetFullSnapshot() bool {
	if x != nil {
		return x.FullSnapshot
	}
	return false
}

// ArgusSecurityPolicyItem 单条安全策略条目，对应 CRD ArgusSecurityPolicy。
type ArgusSecurityPolicyItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Mode          string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	FailureMode   string                 `protobuf:"bytes,4,opt,name=failure_mode,json=failureMode,proto3" json:"failure_mode,omitempty"`
	Providers     []string               `protobuf:"bytes,5,rep,name=providers,proto3" json:"providers,omitempty"`
	Detectors     *DetectorConfig        `protobuf:"bytes,6,opt,name=detectors,proto3" json:"detectors,omitempty"`
	Thresholds    *ThresholdConfig       `protobuf:"bytes,7,opt,name=thresholds,proto3" json:"thresholds,omitempty"`
	Scope         *ScopeConfig           `protobuf:"bytes,8,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArgusSecurityPolicyItem) Reset() {
	*x = ArgusSecurityPolicyItem{}
	mi := &file_argus_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArgusSecurityPolicyItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArgusSecurityPolicyItem) ProtoMessage() {}

func (x *ArgusSecurityPolicyItem) ProtoReflect() protoreflect.Message {
	mi := &file_argus_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArgusSecurityPolicyItem.ProtoReflect.Descriptor instead.
func (*ArgusSecurityPolicyItem) Descriptor() ([]byte, []int) {
	return file_argus_policy_proto_rawDescGZIP(), []int{2}
}

func (x *ArgusSecurityPolicyItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ArgusSecurityPolicyItem) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ArgusSecurityPolicyItem) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *ArgusSecurityPolicyItem) GetFailureMode() string {
	if x != nil {
		return x.FailureMode
	}
	return ""
}

func (x *ArgusSecurityPolicyItem) GetProviders() []string {
	if x != nil {
		return x.Providers
	}
	return nil
}

func (x *ArgusSecurityPolicyItem) GetDetectors() *DetectorConfig {
	if x != nil {
		return x.Detectors
	}
	return nil
}

func (x *ArgusSecurityPolicyItem) GetThresholds() *ThresholdConfig {
	if x != nil {
		return x.Thresholds
	}
	return nil
}

func (x *ArgusSecurityPolicyItem) GetScope() *ScopeConfig {
	if x != nil {
		return x.Scope
	}
	return nil
}

// DetectorConfig 配置各检测器开关与参数。
type DetectorConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         *RulesDetectorConfig   `protobuf:"bytes,1,opt,name=rules,proto3" json:"rules,omitempty"`
	Heuristic     *SimpleToggle          `protobuf:"bytes,2,opt,name=heuristic,proto3" json:"heuristic,omitempty"`
	Encoding      *SimpleToggle          `protobuf:"bytes,3,opt,name=encoding,proto3" json:"encoding,omitempty"`
	Semantic      *SimpleToggle          `protobuf:"bytes,4,opt,name=semantic,proto3" json:"semantic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectorConfig) Reset() {
	*x = DetectorConfig{}
	mi := &file_argus_policy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectorConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectorConfig) ProtoMessage() {}

func (x *DetectorConfig) ProtoReflect() protoreflect.Message {
	mi := &file_argus_policy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectorConfig.ProtoReflect.Descriptor instead.
func (*DetectorConfig) Descriptor() ([]byte, []int) {
	return file_argus_policy_proto_rawDescGZIP(), []int{3}
}

func (x *DetectorConfig) GetRules() *RulesDetectorConfig {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *DetectorConfig) GetHeuristic() *SimpleToggle {
	if x != nil {
		return x.Heuristic
	}
	return nil
}

func (x *DetectorConfig) GetEncoding() *SimpleToggle {
	if x != nil {
		return x.Encoding
	}
	return nil
}

func (x *DetectorConfig) GetSemantic() *SimpleToggle {
	if x != nil {
		return x.Semantic
	}
	return nil
}

// RulesDetectorConfig 基于规则的检测器配置。
type RulesDetectorConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Rules         []*RuleSpec            `protobuf:"bytes,2,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RulesDetectorConfig) Reset() {
	*x = RulesDetectorConfig{}
	mi := &file_argus_policy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RulesDetectorConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RulesDetectorConfig) ProtoMessage() {}

func (x *RulesDetectorConfig) ProtoReflect() protoreflect.Message {
	mi := &file_argus_policy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RulesDetectorConfig.ProtoReflect.Descriptor instead.
func (*RulesDetectorConfig) Descriptor() ([]byte, []int) {
	return file_argus_policy_proto_rawDescGZIP(), []int{4}
}

func (x *RulesDetectorConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *RulesDetectorConfig) GetRules() []*RuleSpec {
	if x != nil {
		return x.Rules
	}
	return nil
}

// RuleSpec 单条规则定义，含匹配模式与权重。
type RuleSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Pattern       string                 `protobuf:"bytes,2,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Weight        float64                `protobuf:"fixed64,4,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleSpec) Reset() {
	*x = RuleSpec{}
	mi := &file_argus_policy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleSpec) ProtoMessage() {}

func (x *RuleSpec) ProtoReflect() protoreflect.Message {
	mi := &file_argus_policy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleSpec.ProtoReflect.Descriptor instead.
func (*RuleSpec) Descriptor() ([]byte, []int) {
	return file_argus_policy_proto_rawDescGZIP(), []int{5}
}

func (x *RuleSpec) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RuleSpec) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *RuleSpec) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RuleSpec) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

// SimpleToggle 简单开关型配置。
type SimpleToggle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimpleToggle) Reset() {
	*x = SimpleToggle{}
	mi := &file_argus_policy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleToggle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleToggle) ProtoMessage() {}

func (x *SimpleToggle) ProtoReflect() protoreflect.Message {
	mi := &file_argus_policy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleToggle.ProtoReflect.Descriptor instead.
func (*SimpleToggle) Descriptor() ([]byte, []int) {
	return file_argus_policy_proto_rawDescGZIP(), []int{6}
}

func (x *SimpleToggle) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

// ThresholdConfig 风险阈值配置，决定 log / block 行为。
type ThresholdConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockScore    float64                `protobuf:"fixed64,1,opt,name=block_score,json=blockScore,proto3" json:"block_score,omitempty"`
	LogScore      float64                `protobuf:"fixed64,2,opt,name=log_score,json=logScore,proto3" json:"log_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThresholdConfig) Reset() {
	*x = ThresholdConfig{}
	mi := &file_argus_policy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThresholdConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThresholdConfig) ProtoMessage() {}

func (x *ThresholdConfig) ProtoReflect() protoreflect.Message {
	mi := &file_argus_policy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThresholdConfig.ProtoReflect.Descriptor instead.
func (*ThresholdConfig) Descriptor() ([]byte, []int) {
	return file_argus_policy_proto_rawDescGZIP(), []int{7}
}

func (x *ThresholdConfig) GetBlockScore() float64 {
	if x != nil {
		return x.BlockScore
	}
	return 0
}

func (x *ThresholdConfig) GetLogScore() float64 {
	if x != nil {
		return x.LogScore
	}
	return 0
}

// ScopeConfig 策略生效范围：命名空间 + 工作负载匹配。
type ScopeConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespaces    []string               `protobuf:"bytes,1,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	Workloads     []*WorkloadMatch       `protobuf:"bytes,2,rep,name=workloads,proto3" json:"workloads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScopeConfig) Reset() {
	*x = ScopeConfig{}
	mi := &file_argus_policy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScopeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScopeConfig) ProtoMessage() {}

func (x *ScopeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_argus_policy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScopeConfig.ProtoReflect.Descriptor instead.
func (*ScopeConfig) Descriptor() ([]byte, []int) {
	return file_argus_policy_proto_rawDescGZIP(), []int{8}
}

func (x *ScopeConfig) GetNamespaces() []string {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

func (x *ScopeConfig) GetWorkloads() []*WorkloadMatch {
	if x != nil {
		return x.Workloads
	}
	return nil
}

// WorkloadMatch 按 kind + name 匹配工作负载。
type WorkloadMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadMatch) Reset() {
	*x = WorkloadMatch{}
	mi := &file_argus_policy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadMatch) ProtoMessage() {}

func (x *WorkloadMatch) ProtoReflect() protoreflect.Message {
	mi := &file_argus_policy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadMatch.ProtoReflect.Descriptor instead.
func (*WorkloadMatch) Descriptor() ([]byte, []int) {
	return file_argus_policy_proto_rawDescGZIP(), []int{9}
}

func (x *WorkloadMatch) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *WorkloadMatch) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// ProviderSnapshot Controller 下发的 LLMProvider 配置快照。
type ProviderSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Items         []*LLMProviderItem     `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	FullSnapshot  bool                   `protobuf:"varint,3,opt,name=full_snapshot,json=fullSnapshot,proto3" json:"full_snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderSnapshot) Reset() {
	*x = ProviderSnapshot{}
	mi := &file_argus_policy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderSnapshot) ProtoMessage() {}

func (x *ProviderSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_argus_policy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderSnapshot.ProtoReflect.Descriptor instead.
func (*ProviderSnapshot) Descriptor() ([]byte, []int) {
	return file_argus_policy_proto_rawDescGZIP(), []int{10}
}

func (x *ProviderSnapshot) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ProviderSnapshot) GetItems() []*LLMProviderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ProviderSnapshot) GetFullSnapshot() bool {
	if x != nil {
		return x.FullSnapshot
	}
	return false
}

// LLMProviderItem 单条 LLM Provider 配置条目，对应 CRD LLMProvider。
type LLMProviderItem struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace         string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Type              string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Hosts             []string               `protobuf:"bytes,4,rep,name=hosts,proto3" json:"hosts,omitempty"`
	Sni               []string               `protobuf:"bytes,5,rep,name=sni,proto3" json:"sni,omitempty"`
	Upstream          *UpstreamConfig        `protobuf:"bytes,6,opt,name=upstream,proto3" json:"upstream,omitempty"`
	Adapter           string                 `protobuf:"bytes,7,opt,name=adapter,proto3" json:"adapter,omitempty"`
	Models            []string               `protobuf:"bytes,8,rep,name=models,proto3" json:"models,omitempty"`
	SkipTlsInspection bool                   `protobuf:"varint,9,opt,name=skip_tls_inspection,json=skipTlsInspection,proto3" json:"skip_tls_inspection,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LLMProviderItem) Reset() {
	*x = LLMProviderItem{}
	mi := &file_argus_policy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMProviderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMProviderItem) ProtoMessage() {}

func (x *LLMProviderItem) ProtoReflect() protoreflect.Message {
	mi := &file_argus_policy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMProviderItem.ProtoReflect.Descriptor instead.
func (*LLMProviderItem) Descriptor() ([]byte, []int) {
	return file_argus_policy_proto_rawDescGZIP(), []int{11}
}

func (x *LLMProviderItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LLMProviderItem) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *LLMProviderItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LLMProviderItem) GetHosts() []string {
	if x != nil {
		return x.Hosts
	}
	return nil
}

func (x *LLMProviderItem) GetSni() []string {
	if x != nil {
		return x.Sni
	}
	return nil
}

func (x *LLMProviderItem) GetUpstream() *UpstreamConfig {
	if x != nil {
		return x.Upstream
	}
	return nil
}

func (x *LLMProviderItem) GetAdapter() string {
	if x != nil {
		return x.Adapter
	}
	return ""
}

func (x *LLMProviderItem) GetModels() []string {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *LLMProviderItem) GetSkipTlsInspection() bool {
	if x != nil {
		return x.SkipTlsInspection
	}
	return false
}

// UpstreamConfig Provider 上游连接配置。
type UpstreamConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scheme        string                 `protobuf:"bytes,1,opt,name=scheme,proto3" json:"scheme,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpstreamConfig) Reset() {
	*x = UpstreamConfig{}
	mi := &file_argus_policy_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpstreamConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpstreamConfig) ProtoMessage() {}

func (x *UpstreamConfig) ProtoReflect() protoreflect.Message {
	mi := &file_argus_policy_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpstreamConfig.ProtoReflect.Descriptor instead.
func (*UpstreamConfig) Descriptor() ([]byte, []int) {
	return file_argus_policy_proto_rawDescGZIP(), []int{12}
}

func (x *UpstreamConfig) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

var File_argus_policy_proto protoreflect.FileDescriptor

const file_argus_policy_proto_rawDesc = "" +
	"\n" +
	"\x12argus/policy.proto\x12\x15argus.policy.v1alpha1\"[\n" +
	"\fWatchRequest\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x01 \x01(\tR\tgatewayId\x12,\n" +
	"\x12last_known_version\x18\x02 \x01(\tR\x10lastKnownVersion\"\x95\x01\n" +
	"\x0ePolicySnapshot\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x12D\n" +
	"\x05items\x18\x02 \x03(\v2..argus.policy.v1alpha1.ArgusSecurityPolicyItemR\x05items\x12#\n" +
	"\rfull_snapshot\x18\x03 \x01(\bR\ffullSnapshot\"\xe7\x02\n" +
	"\x17ArgusSecurityPolicyItem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\x12!\n" +
	"\ffailure_mode\x18\x04 \x01(\tR\vfailureMode\x12\x1c\n" +
	"\tproviders\x18\x05 \x03(\tR\tproviders\x12C\n" +
	"\tdetectors\x18\x06 \x01(\v2%.argus.policy.v1alpha1.DetectorConfigR\tdetectors\x12F\n" +
	"\n" +
	"thresholds\x18\a \x01(\v2&.argus.policy.v1alpha1.ThresholdConfigR\n" +
	"thresholds\x128\n" +
	"\x05scope\x18\b \x01(\v2\".argus.policy.v1alpha1.ScopeConfigR\x05scope\"\x97\x02\n" +
	"\x0eDetectorConfig\x12@\n" +
	"\x05rules\x18\x01 \x01(\v2*.argus.policy.v1alpha1.RulesDetectorConfigR\x05rules\x12A\n" +
	"\theuristic\x18\x02 \x01(\v2#.argus.policy.v1alpha1.SimpleToggleR\theuristic\x12?\n" +
	"\bencoding\x18\x03 \x01(\v2#.argus.policy.v1alpha1.SimpleToggleR\bencoding\x12?\n" +
	"\bsemantic\x18\x04 \x01(\v2#.argus.policy.v1alpha1.SimpleToggleR\bsemantic\"f\n" +
	"\x13RulesDetectorConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x125\n" +
	"\x05rules\x18\x02 \x03(\v2\x1f.argus.policy.v1alpha1.RuleSpecR\x05rules\"`\n" +
	"\bRuleSpec\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\apattern\x18\x02 \x01(\tR\apattern\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\x01R\x06weight\"(\n" +
	"\fSimpleToggle\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\"O\n" +
	"\x0fThresholdConfig\x12\x1f\n" +
	"\vblock_score\x18\x01 \x01(\x01R\n" +
	"blockScore\x12\x1b\n" +
	"\tlog_score\x18\x02 \x01(\x01R\blogScore\"q\n" +
	"\vScopeConfig\x12\x1e\n" +
	"\n" +
	"namespaces\x18\x01 \x03(\tR\n" +
	"namespaces\x12B\n" +
	"\tworkloads\x18\x02 \x03(\v2$.argus.policy.v1alpha1.WorkloadMatchR\tworkloads\"7\n" +
	"\rWorkloadMatch\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x8f\x01\n" +
	"\x10ProviderSnapshot\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x12<\n" +
	"\x05items\x18\x02 \x03(\v2&.argus.policy.v1alpha1.LLMProviderItemR\x05items\x12#\n" +
	"\rfull_snapshot\x18\x03 \x01(\bR\ffullSnapshot\"\xa4\x02\n" +
	"\x0fLLMProviderItem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05hosts\x18\x04 \x03(\tR\x05hosts\x12\x10\n" +
	"\x03sni\x18\x05 \x03(\tR\x03sni\x12A\n" +
	"\bupstream\x18\x06 \x01(\v2%.argus.policy.v1alpha1.UpstreamConfigR\bupstream\x12\x18\n" +
	"\aadapter\x18\a \x01(\tR\aadapter\x12\x16\n" +
	"\x06models\x18\b \x03(\tR\x06models\x12.\n" +
	"\x13skip_tls_inspection\x18\t \x01(\bR\x11skipTlsInspection\"(\n" +
	"\x0eUpstreamConfig\x12\x16\n" +
	"\x06scheme\x18\x01 \x01(\tR\x06scheme2\xd4\x01\n" +
	"\rPolicyService\x12_\n" +
	"\rWatchPolicies\x12#.argus.policy.v1alpha1.WatchRequest\x1a%.argus.policy.v1alpha1.PolicySnapshot(\x010\x01\x12b\n" +
	"\x0eWatchProviders\x12#.argus.policy.v1alpha1.WatchRequest\x1a'.argus.policy.v1alpha1.ProviderSnapshot(\x010\x01B?Z=github.com/ctkqiang/argus/pkg/pb/argus/policy/v1alpha1;policyb\x06proto3"

var (
	file_argus_policy_proto_rawDescOnce sync.Once
	file_argus_policy_proto_rawDescData []byte
)

func file_argus_policy_proto_rawDescGZIP() []byte {
	file_argus_policy_proto_rawDescOnce.Do(func() {
		file_argus_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_argus_policy_proto_rawDesc), len(file_argus_policy_proto_rawDesc)))
	})
	return file_argus_policy_proto_rawDescData
}

var file_argus_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_argus_policy_proto_goTypes = []any{
	(*WatchRequest)(nil),            // 0: argus.policy.v1alpha1.WatchRequest
	(*PolicySnapshot)(nil),          // 1: argus.policy.v1alpha1.PolicySnapshot
	(*ArgusSecurityPolicyItem)(nil), // 2: argus.policy.v1alpha1.ArgusSecurityPolicyItem
	(*DetectorConfig)(nil),          // 3: argus.policy.v1alpha1.DetectorConfig
	(*RulesDetectorConfig)(nil),     // 4: argus.policy.v1alpha1.RulesDetectorConfig
	(*RuleSpec)(nil),                // 5: argus.policy.v1alpha1.RuleSpec
	(*SimpleToggle)(nil),            // 6: argus.policy.v1alpha1.SimpleToggle
	(*ThresholdConfig)(nil),         // 7: argus.policy.v1alpha1.ThresholdConfig
	(*ScopeConfig)(nil),             // 8: argus.policy.v1alpha1.ScopeConfig
	(*WorkloadMatch)(nil),           // 9: argus.policy.v1alpha1.WorkloadMatch
	(*ProviderSnapshot)(nil),        // 10: argus.policy.v1alpha1.ProviderSnapshot
	(*LLMProviderItem)(nil),         // 11: argus.policy.v1alpha1.LLMProviderItem
	(*UpstreamConfig)(nil),          // 12: argus.policy.v1alpha1.UpstreamConfig
}
var file_argus_policy_proto_depIdxs = []int32{
	2,  // 0: argus.policy.v1alpha1.PolicySnapshot.items:type_name -> argus.policy.v1alpha1.ArgusSecurityPolicyItem
	3,  // 1: argus.policy.v1alpha1.ArgusSecurityPolicyItem.detectors:type_name -> argus.policy.v1alpha1.DetectorConfig
	7,  // 2: argus.policy.v1alpha1.ArgusSecurityPolicyItem.thresholds:type_name -> argus.policy.v1alpha1.ThresholdConfig
	8,  // 3: argus.policy.v1alpha1.ArgusSecurityPolicyItem.scope:type_name -> argus.policy.v1alpha1.ScopeConfig
	4,  // 4: argus.policy.v1alpha1.DetectorConfig.rules:type_name -> argus.policy.v1alpha1.RulesDetectorConfig
	6,  // 5: argus.policy.v1alpha1.DetectorConfig.heuristic:type_name -> argus.policy.v1alpha1.SimpleToggle
	6,  // 6: argus.policy.v1alpha1.DetectorConfig.encoding:type_name -> argus.policy.v1alpha1.SimpleToggle
	6,  // 7: argus.policy.v1alpha1.DetectorConfig.semantic:type_name -> argus.policy.v1alpha1.SimpleToggle
	5,  // 8: argus.policy.v1alpha1.RulesDetectorConfig.rules:type_name -> argus.policy.v1alpha1.RuleSpec
	9,  // 9: argus.policy.v1alpha1.ScopeConfig.workloads:type_name -> argus.policy.v1alpha1.WorkloadMatch
	11, // 10: argus.policy.v1alpha1.ProviderSnapshot.items:type_name -> argus.policy.v1alpha1.LLMProviderItem
	12, // 11: argus.policy.v1alpha1.LLMProviderItem.upstream:type_name -> argus.policy.v1alpha1.UpstreamConfig
	0,  // 12: argus.policy.v1alpha1.PolicyService.WatchPolicies:input_type -> argus.policy.v1alpha1.WatchRequest
	0,  // 13: argus.policy.v1alpha1.PolicyService.WatchProviders:input_type -> argus.policy.v1alpha1.WatchRequest
	1,  // 14: argus.policy.v1alpha1.PolicyService.WatchPolicies:output_type -> argus.policy.v1alpha1.PolicySnapshot
	10, // 15: argus.policy.v1alpha1.PolicyService.WatchProviders:output_type -> argus.policy.v1alpha1.ProviderSnapshot
	14, // [14:16] is the sub-list for method output_type
	12, // [12:14] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_argus_policy_proto_init() }
func file_argus_policy_proto_init() {
	if File_argus_policy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_argus_policy_proto_rawDesc), len(file_argus_policy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_argus_policy_proto_goTypes,
		DependencyIndexes: file_argus_policy_proto_depIdxs,
		MessageInfos:      file_argus_policy_proto_msgTypes,
	}.Build()
	File_argus_policy_proto = out.File
	file_argus_policy_proto_goTypes = nil
	file_argus_policy_proto_depIdxs = nil
}
