//
//Argus 观枢 - PolicyService 策略下发契约
//本文件定义 Controller 向 Gateway 下发 ArgusSecurityPolicy 和 LLMProvider
//配置的双向流式 gRPC 服务。Gateway 发起 watch，Controller 推送全量+增量快照。

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: argus/policy.proto

package policy

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PolicyService_WatchPolicies_FullMethodName  = "/argus.policy.v1alpha1.PolicyService/WatchPolicies"
	PolicyService_WatchProviders_FullMethodName = "/argus.policy.v1alpha1.PolicyService/WatchProviders"
)

// PolicyServiceClient is the client API for PolicyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PolicyService 定义策略与 Provider 配置下发服务。
type PolicyServiceClient interface {
	// WatchPolicies 双向流式监听 ArgusSecurityPolicy 变更。
	// Gateway 发送自身 ID 与已知版本号，Controller 推送全量或增量快照。
	WatchPolicies(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WatchRequest, PolicySnapshot], error)
	// WatchProviders 双向流式监听 LLMProvider 配置变更。
	WatchProviders(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WatchRequest, ProviderSnapshot], error)
}

type policyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPolicyServiceClient(cc grpc.ClientConnInterface) PolicyServiceClient {
	return &policyServiceClient{cc}
}

func (c *policyServiceClient) WatchPolicies(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WatchRequest, PolicySnapshot], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PolicyService_ServiceDesc.Streams[0], PolicyService_WatchPolicies_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, PolicySnapshot]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PolicyService_WatchPoliciesClient = grpc.BidiStreamingClient[WatchRequest, PolicySnapshot]

func (c *policyServiceClient) WatchProviders(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WatchRequest, ProviderSnapshot], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PolicyService_ServiceDesc.Streams[1], PolicyService_WatchProviders_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, ProviderSnapshot]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PolicyService_WatchProvidersClient = grpc.BidiStreamingClient[WatchRequest, ProviderSnapshot]

// PolicyServiceServer is the server API for PolicyService service.
// All implementations should embed UnimplementedPolicyServiceServer
// for forward compatibility.
//
// PolicyService 定义策略与 Provider 配置下发服务。
type PolicyServiceServer interface {
	// WatchPolicies 双向流式监听 ArgusSecurityPolicy 变更。
	// Gateway 发送自身 ID 与已知版本号，Controller 推送全量或增量快照。
	WatchPolicies(grpc.BidiStreamingServer[WatchRequest, PolicySnapshot]) error
	// WatchProviders 双向流式监听 LLMProvider 配置变更。
	WatchProviders(grpc.BidiStreamingServer[WatchRequest, ProviderSnapshot]) error
}

// UnimplementedPolicyServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPolicyServiceServer struct{}

func (UnimplementedPolicyServiceServer) WatchPolicies(grpc.BidiStreamingServer[WatchRequest, PolicySnapshot]) error {
	return status.Error(codes.Unimplemented, "method WatchPolicies not implemented")
}
func (UnimplementedPolicyServiceServer) WatchProviders(grpc.BidiStreamingServer[WatchRequest, ProviderSnapshot]) error {
	return status.Error(codes.Unimplemented, "method WatchProviders not implemented")
}
func (UnimplementedPolicyServiceServer) testEmbeddedByValue() {}

// UnsafePolicyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PolicyServiceServer will
// result in compilation errors.
type UnsafePolicyServiceServer interface {
	mustEmbedUnimplementedPolicyServiceServer()
}

func RegisterPolicyServiceServer(s grpc.ServiceRegistrar, srv PolicyServiceServer) {
	// If the following call panics, it indicates UnimplementedPolicyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PolicyService_ServiceDesc, srv)
}

func _PolicyService_WatchPolicies_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PolicyServiceServer).WatchPolicies(&grpc.GenericServerStream[WatchRequest, PolicySnapshot]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PolicyService_WatchPoliciesServer = grpc.BidiStreamingServer[WatchRequest, PolicySnapshot]

func _PolicyService_WatchProviders_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PolicyServiceServer).WatchProviders(&grpc.GenericServerStream[WatchRequest, ProviderSnapshot]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PolicyService_WatchProvidersServer = grpc.BidiStreamingServer[WatchRequest, ProviderSnapshot]

// PolicyService_ServiceDesc is the grpc.ServiceDesc for PolicyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PolicyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "argus.policy.v1alpha1.PolicyService",
	HandlerType: (*PolicyServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchPolicies",
			Handler:       _PolicyService_WatchPolicies_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "WatchProviders",
			Handler:       _PolicyService_WatchProviders_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "argus/policy.proto",
}
