{{- if not .Values.controller.serviceAccount.name }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "argus.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
  labels: {{ include "argus.labels" . | nindent 4 }}
{{- end }}
