{{- if .Values.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "argus.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "argus.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{ include "argus.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
{{- end }}
