apiVersion: v1
kind: Service
metadata:
  name: {{ include "argus.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "argus.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
spec:
  type: {{ .Values.controller.service.type }}
  selector:
    {{- include "argus.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: controller
  ports:
    - name: grpc
      port: {{ .Values.controller.service.port }}
      targetPort: {{ .Values.controller.service.port }}
    - name: metrics
      port: 9090
      targetPort: 9090
