//
//Argus 观枢 - DetectionService 检测服务契约
//本文件定义 Gateway 内部调用的 Prompt 检测器流水线抽象接口。
//支持单请求 Detect 和流式 DetectStream，便于后续替换为进程外远程检测器。

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: argus/detection.proto

package detection

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DetectionService_Detect_FullMethodName       = "/argus.detection.v1alpha1.DetectionService/Detect"
	DetectionService_DetectStream_FullMethodName = "/argus.detection.v1alpha1.DetectionService/DetectStream"
)

// DetectionServiceClient is the client API for DetectionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DetectionService 定义 Prompt 安全检测服务。
type DetectionServiceClient interface {
	// Detect 单次同步检测请求，返回检测结果与综合风险评分。
	Detect(ctx context.Context, in *DetectRequest, opts ...grpc.CallOption) (*DetectResponse, error)
	// DetectStream 流式检测，适合逐 token 或多轮会话场景。
	DetectStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DetectRequest, DetectResponse], error)
}

type detectionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDetectionServiceClient(cc grpc.ClientConnInterface) DetectionServiceClient {
	return &detectionServiceClient{cc}
}

func (c *detectionServiceClient) Detect(ctx context.Context, in *DetectRequest, opts ...grpc.CallOption) (*DetectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetectResponse)
	err := c.cc.Invoke(ctx, DetectionService_Detect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *detectionServiceClient) DetectStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DetectRequest, DetectResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DetectionService_ServiceDesc.Streams[0], DetectionService_DetectStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DetectRequest, DetectResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DetectionService_DetectStreamClient = grpc.BidiStreamingClient[DetectRequest, DetectResponse]

// DetectionServiceServer is the server API for DetectionService service.
// All implementations should embed UnimplementedDetectionServiceServer
// for forward compatibility.
//
// DetectionService 定义 Prompt 安全检测服务。
type DetectionServiceServer interface {
	// Detect 单次同步检测请求，返回检测结果与综合风险评分。
	Detect(context.Context, *DetectRequest) (*DetectResponse, error)
	// DetectStream 流式检测，适合逐 token 或多轮会话场景。
	DetectStream(grpc.BidiStreamingServer[DetectRequest, DetectResponse]) error
}

// UnimplementedDetectionServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDetectionServiceServer struct{}

func (UnimplementedDetectionServiceServer) Detect(context.Context, *DetectRequest) (*DetectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Detect not implemented")
}
func (UnimplementedDetectionServiceServer) DetectStream(grpc.BidiStreamingServer[DetectRequest, DetectResponse]) error {
	return status.Error(codes.Unimplemented, "method DetectStream not implemented")
}
func (UnimplementedDetectionServiceServer) testEmbeddedByValue() {}

// UnsafeDetectionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DetectionServiceServer will
// result in compilation errors.
type UnsafeDetectionServiceServer interface {
	mustEmbedUnimplementedDetectionServiceServer()
}

func RegisterDetectionServiceServer(s grpc.ServiceRegistrar, srv DetectionServiceServer) {
	// If the following call panics, it indicates UnimplementedDetectionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DetectionService_ServiceDesc, srv)
}

func _DetectionService_Detect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DetectionServiceServer).Detect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DetectionService_Detect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DetectionServiceServer).Detect(ctx, req.(*DetectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DetectionService_DetectStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DetectionServiceServer).DetectStream(&grpc.GenericServerStream[DetectRequest, DetectResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DetectionService_DetectStreamServer = grpc.BidiStreamingServer[DetectRequest, DetectResponse]

// DetectionService_ServiceDesc is the grpc.ServiceDesc for DetectionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DetectionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "argus.detection.v1alpha1.DetectionService",
	HandlerType: (*DetectionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Detect",
			Handler:    _DetectionService_Detect_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DetectStream",
			Handler:       _DetectionService_DetectStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "argus/detection.proto",
}
