//
//Argus 观枢 - DetectionService 检测服务契约
//本文件定义 Gateway 内部调用的 Prompt 检测器流水线抽象接口。
//支持单请求 Detect 和流式 DetectStream，便于后续替换为进程外远程检测器。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: argus/detection.proto

package detection

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LLMRequest 解析后的大模型出站请求结构化数据。
type LLMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Adapter       string                 `protobuf:"bytes,2,opt,name=adapter,proto3" json:"adapter,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Messages      []*ChatMessage         `protobuf:"bytes,4,rep,name=messages,proto3" json:"messages,omitempty"`
	System        string                 `protobuf:"bytes,5,opt,name=system,proto3" json:"system,omitempty"`
	Tools         []*ToolDef             `protobuf:"bytes,6,rep,name=tools,proto3" json:"tools,omitempty"`
	PromptParts   []string               `protobuf:"bytes,7,rep,name=prompt_parts,json=promptParts,proto3" json:"prompt_parts,omitempty"`
	Path          string                 `protobuf:"bytes,8,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LLMRequest) Reset() {
	*x = LLMRequest{}
	mi := &file_argus_detection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMRequest) ProtoMessage() {}

func (x *LLMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_argus_detection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMRequest.ProtoReflect.Descriptor instead.
func (*LLMRequest) Descriptor() ([]byte, []int) {
	return file_argus_detection_proto_rawDescGZIP(), []int{0}
}

func (x *LLMRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *LLMRequest) GetAdapter() string {
	if x != nil {
		return x.Adapter
	}
	return ""
}

func (x *LLMRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *LLMRequest) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *LLMRequest) GetSystem() string {
	if x != nil {
		return x.System
	}
	return ""
}

func (x *LLMRequest) GetTools() []*ToolDef {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *LLMRequest) GetPromptParts() []string {
	if x != nil {
		return x.PromptParts
	}
	return nil
}

func (x *LLMRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// ChatMessage 单条对话消息，含角色、内容、可选工具调用。
type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ToolCalls     []*ToolCall            `protobuf:"bytes,4,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_argus_detection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_argus_detection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_argus_detection_proto_rawDescGZIP(), []int{1}
}

func (x *ChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChatMessage) GetToolCalls() []*ToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

// ToolCall LLM 发起的工具调用请求。
type ToolCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Function      *FunctionCall          `protobuf:"bytes,3,opt,name=function,proto3" json:"function,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_argus_detection_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_argus_detection_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_argus_detection_proto_rawDescGZIP(), []int{2}
}

func (x *ToolCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCall) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ToolCall) GetFunction() *FunctionCall {
	if x != nil {
		return x.Function
	}
	return nil
}

// FunctionCall 函数调用的名称与序列化参数。
type FunctionCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Arguments     string                 `protobuf:"bytes,2,opt,name=arguments,proto3" json:"arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionCall) Reset() {
	*x = FunctionCall{}
	mi := &file_argus_detection_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionCall) ProtoMessage() {}

func (x *FunctionCall) ProtoReflect() protoreflect.Message {
	mi := &file_argus_detection_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionCall.ProtoReflect.Descriptor instead.
func (*FunctionCall) Descriptor() ([]byte, []int) {
	return file_argus_detection_proto_rawDescGZIP(), []int{3}
}

func (x *FunctionCall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionCall) GetArguments() string {
	if x != nil {
		return x.Arguments
	}
	return ""
}

// ToolDef 客户端声明的可用工具定义。
type ToolDef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Function      *FunctionDef           `protobuf:"bytes,2,opt,name=function,proto3" json:"function,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolDef) Reset() {
	*x = ToolDef{}
	mi := &file_argus_detection_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolDef) ProtoMessage() {}

func (x *ToolDef) ProtoReflect() protoreflect.Message {
	mi := &file_argus_detection_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolDef.ProtoReflect.Descriptor instead.
func (*ToolDef) Descriptor() ([]byte, []int) {
	return file_argus_detection_proto_rawDescGZIP(), []int{4}
}

func (x *ToolDef) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ToolDef) GetFunction() *FunctionDef {
	if x != nil {
		return x.Function
	}
	return nil
}

// FunctionDef 函数工具的元信息与 JSON Schema 参数描述。
type FunctionDef struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ParametersJson string                 `protobuf:"bytes,3,opt,name=parameters_json,json=parametersJson,proto3" json:"parameters_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FunctionDef) Reset() {
	*x = FunctionDef{}
	mi := &file_argus_detection_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionDef) ProtoMessage() {}

func (x *FunctionDef) ProtoReflect() protoreflect.Message {
	mi := &file_argus_detection_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionDef.ProtoReflect.Descriptor instead.
func (*FunctionDef) Descriptor() ([]byte, []int) {
	return file_argus_detection_proto_rawDescGZIP(), []int{5}
}

func (x *FunctionDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionDef) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FunctionDef) GetParametersJson() string {
	if x != nil {
		return x.ParametersJson
	}
	return ""
}

// DetectionContext 多轮会话检测上下文，供语义检测器参考历史。
type DetectionContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	History       []*LLMRequest          `protobuf:"bytes,2,rep,name=history,proto3" json:"history,omitempty"`
	RoundIndex    int32                  `protobuf:"varint,3,opt,name=round_index,json=roundIndex,proto3" json:"round_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectionContext) Reset() {
	*x = DetectionContext{}
	mi := &file_argus_detection_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectionContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectionContext) ProtoMessage() {}

func (x *DetectionContext) ProtoReflect() protoreflect.Message {
	mi := &file_argus_detection_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectionContext.ProtoReflect.Descriptor instead.
func (*DetectionContext) Descriptor() ([]byte, []int) {
	return file_argus_detection_proto_rawDescGZIP(), []int{6}
}

func (x *DetectionContext) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DetectionContext) GetHistory() []*LLMRequest {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *DetectionContext) GetRoundIndex() int32 {
	if x != nil {
		return x.RoundIndex
	}
	return 0
}

// DetectRequest 检测器输入：当前请求 + 会话上下文 + 策略名。
type DetectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *LLMRequest            `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Context       *DetectionContext      `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	PolicyName    string                 `protobuf:"bytes,3,opt,name=policy_name,json=policyName,proto3" json:"policy_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectRequest) Reset() {
	*x = DetectRequest{}
	mi := &file_argus_detection_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectRequest) ProtoMessage() {}

func (x *DetectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_argus_detection_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectRequest.ProtoReflect.Descriptor instead.
func (*DetectRequest) Descriptor() ([]byte, []int) {
	return file_argus_detection_proto_rawDescGZIP(), []int{7}
}

func (x *DetectRequest) GetRequest() *LLMRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *DetectRequest) GetContext() *DetectionContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *DetectRequest) GetPolicyName() string {
	if x != nil {
		return x.PolicyName
	}
	return ""
}

// DetectResponse 检测器输出：各检测器明细结果 + 综合风险分。
type DetectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*DetectionResult     `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	RiskScore     float64                `protobuf:"fixed64,2,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectResponse) Reset() {
	*x = DetectResponse{}
	mi := &file_argus_detection_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectResponse) ProtoMessage() {}

func (x *DetectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_argus_detection_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectResponse.ProtoReflect.Descriptor instead.
func (*DetectResponse) Descriptor() ([]byte, []int) {
	return file_argus_detection_proto_rawDescGZIP(), []int{8}
}

func (x *DetectResponse) GetResults() []*DetectionResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *DetectResponse) GetRiskScore() float64 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

// DetectionResult 单个检测器的检测结果明细。
type DetectionResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Detector      string                 `protobuf:"bytes,1,opt,name=detector,proto3" json:"detector,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Score         float64                `protobuf:"fixed64,3,opt,name=score,proto3" json:"score,omitempty"`
	Matched       bool                   `protobuf:"varint,4,opt,name=matched,proto3" json:"matched,omitempty"`
	Evidence      string                 `protobuf:"bytes,5,opt,name=evidence,proto3" json:"evidence,omitempty"`
	MatchedRanges []string               `protobuf:"bytes,6,rep,name=matched_ranges,json=matchedRanges,proto3" json:"matched_ranges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectionResult) Reset() {
	*x = DetectionResult{}
	mi := &file_argus_detection_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectionResult) ProtoMessage() {}

func (x *DetectionResult) ProtoReflect() protoreflect.Message {
	mi := &file_argus_detection_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectionResult.ProtoReflect.Descriptor instead.
func (*DetectionResult) Descriptor() ([]byte, []int) {
	return file_argus_detection_proto_rawDescGZIP(), []int{9}
}

func (x *DetectionResult) GetDetector() string {
	if x != nil {
		return x.Detector
	}
	return ""
}

func (x *DetectionResult) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DetectionResult) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *DetectionResult) GetMatched() bool {
	if x != nil {
		return x.Matched
	}
	return false
}

func (x *DetectionResult) GetEvidence() string {
	if x != nil {
		return x.Evidence
	}
	return ""
}

func (x *DetectionResult) GetMatchedRanges() []string {
	if x != nil {
		return x.MatchedRanges
	}
	return nil
}

var File_argus_detection_proto protoreflect.FileDescriptor

const file_argus_detection_proto_rawDesc = "" +
	"\n" +
	"\x15argus/detection.proto\x12\x18argus.detection.v1alpha1\"\xa3\x02\n" +
	"\n" +
	"LLMRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x18\n" +
	"\aadapter\x18\x02 \x01(\tR\aadapter\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12A\n" +
	"\bmessages\x18\x04 \x03(\v2%.argus.detection.v1alpha1.ChatMessageR\bmessages\x12\x16\n" +
	"\x06system\x18\x05 \x01(\tR\x06system\x127\n" +
	"\x05tools\x18\x06 \x03(\v2!.argus.detection.v1alpha1.ToolDefR\x05tools\x12!\n" +
	"\fprompt_parts\x18\a \x03(\tR\vpromptParts\x12\x12\n" +
	"\x04path\x18\b \x01(\tR\x04path\"\x92\x01\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12A\n" +
	"\n" +
	"tool_calls\x18\x04 \x03(\v2\".argus.detection.v1alpha1.ToolCallR\ttoolCalls\"r\n" +
	"\bToolCall\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12B\n" +
	"\bfunction\x18\x03 \x01(\v2&.argus.detection.v1alpha1.FunctionCallR\bfunction\"@\n" +
	"\fFunctionCall\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\targuments\x18\x02 \x01(\tR\targuments\"`\n" +
	"\aToolDef\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12A\n" +
	"\bfunction\x18\x02 \x01(\v2%.argus.detection.v1alpha1.FunctionDefR\bfunction\"l\n" +
	"\vFunctionDef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12'\n" +
	"\x0fparameters_json\x18\x03 \x01(\tR\x0eparametersJson\"\x92\x01\n" +
	"\x10DetectionContext\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12>\n" +
	"\ahistory\x18\x02 \x03(\v2$.argus.detection.v1alpha1.LLMRequestR\ahistory\x12\x1f\n" +
	"\vround_index\x18\x03 \x01(\x05R\n" +
	"roundIndex\"\xb6\x01\n" +
	"\rDetectRequest\x12>\n" +
	"\arequest\x18\x01 \x01(\v2$.argus.detection.v1alpha1.LLMRequestR\arequest\x12D\n" +
	"\acontext\x18\x02 \x01(\v2*.argus.detection.v1alpha1.DetectionContextR\acontext\x12\x1f\n" +
	"\vpolicy_name\x18\x03 \x01(\tR\n" +
	"policyName\"t\n" +
	"\x0eDetectResponse\x12C\n" +
	"\aresults\x18\x01 \x03(\v2).argus.detection.v1alpha1.DetectionResultR\aresults\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x02 \x01(\x01R\triskScore\"\xb4\x01\n" +
	"\x0fDetectionResult\x12\x1a\n" +
	"\bdetector\x18\x01 \x01(\tR\bdetector\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x01R\x05score\x12\x18\n" +
	"\amatched\x18\x04 \x01(\bR\amatched\x12\x1a\n" +
	"\bevidence\x18\x05 \x01(\tR\bevidence\x12%\n" +
	"\x0ematched_ranges\x18\x06 \x03(\tR\rmatchedRanges2\xd6\x01\n" +
	"\x10DetectionService\x12[\n" +
	"\x06Detect\x12'.argus.detection.v1alpha1.DetectRequest\x1a(.argus.detection.v1alpha1.DetectResponse\x12e\n" +
	"\fDetectStream\x12'.argus.detection.v1alpha1.DetectRequest\x1a(.argus.detection.v1alpha1.DetectResponse(\x010\x01BEZCgithub.com/ctkqiang/argus/pkg/pb/argus/detection/v1alpha1;detectionb\x06proto3"

var (
	file_argus_detection_proto_rawDescOnce sync.Once
	file_argus_detection_proto_rawDescData []byte
)

func file_argus_detection_proto_rawDescGZIP() []byte {
	file_argus_detection_proto_rawDescOnce.Do(func() {
		file_argus_detection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_argus_detection_proto_rawDesc), len(file_argus_detection_proto_rawDesc)))
	})
	return file_argus_detection_proto_rawDescData
}

var file_argus_detection_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_argus_detection_proto_goTypes = []any{
	(*LLMRequest)(nil),       // 0: argus.detection.v1alpha1.LLMRequest
	(*ChatMessage)(nil),      // 1: argus.detection.v1alpha1.ChatMessage
	(*ToolCall)(nil),         // 2: argus.detection.v1alpha1.ToolCall
	(*FunctionCall)(nil),     // 3: argus.detection.v1alpha1.FunctionCall
	(*ToolDef)(nil),          // 4: argus.detection.v1alpha1.ToolDef
	(*FunctionDef)(nil),      // 5: argus.detection.v1alpha1.FunctionDef
	(*DetectionContext)(nil), // 6: argus.detection.v1alpha1.DetectionContext
	(*DetectRequest)(nil),    // 7: argus.detection.v1alpha1.DetectRequest
	(*DetectResponse)(nil),   // 8: argus.detection.v1alpha1.DetectResponse
	(*DetectionResult)(nil),  // 9: argus.detection.v1alpha1.DetectionResult
}
var file_argus_detection_proto_depIdxs = []int32{
	1,  // 0: argus.detection.v1alpha1.LLMRequest.messages:type_name -> argus.detection.v1alpha1.ChatMessage
	4,  // 1: argus.detection.v1alpha1.LLMRequest.tools:type_name -> argus.detection.v1alpha1.ToolDef
	2,  // 2: argus.detection.v1alpha1.ChatMessage.tool_calls:type_name -> argus.detection.v1alpha1.ToolCall
	3,  // 3: argus.detection.v1alpha1.ToolCall.function:type_name -> argus.detection.v1alpha1.FunctionCall
	5,  // 4: argus.detection.v1alpha1.ToolDef.function:type_name -> argus.detection.v1alpha1.FunctionDef
	0,  // 5: argus.detection.v1alpha1.DetectionContext.history:type_name -> argus.detection.v1alpha1.LLMRequest
	0,  // 6: argus.detection.v1alpha1.DetectRequest.request:type_name -> argus.detection.v1alpha1.LLMRequest
	6,  // 7: argus.detection.v1alpha1.DetectRequest.context:type_name -> argus.detection.v1alpha1.DetectionContext
	9,  // 8: argus.detection.v1alpha1.DetectResponse.results:type_name -> argus.detection.v1alpha1.DetectionResult
	7,  // 9: argus.detection.v1alpha1.DetectionService.Detect:input_type -> argus.detection.v1alpha1.DetectRequest
	7,  // 10: argus.detection.v1alpha1.DetectionService.DetectStream:input_type -> argus.detection.v1alpha1.DetectRequest
	8,  // 11: argus.detection.v1alpha1.DetectionService.Detect:output_type -> argus.detection.v1alpha1.DetectResponse
	8,  // 12: argus.detection.v1alpha1.DetectionService.DetectStream:output_type -> argus.detection.v1alpha1.DetectResponse
	11, // [11:13] is the sub-list for method output_type
	9,  // [9:11] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_argus_detection_proto_init() }
func file_argus_detection_proto_init() {
	if File_argus_detection_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_argus_detection_proto_rawDesc), len(file_argus_detection_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_argus_detection_proto_goTypes,
		DependencyIndexes: file_argus_detection_proto_depIdxs,
		MessageInfos:      file_argus_detection_proto_msgTypes,
	}.Build()
	File_argus_detection_proto = out.File
	file_argus_detection_proto_goTypes = nil
	file_argus_detection_proto_depIdxs = nil
}
