apiVersion: v1
kind: Service
metadata:
  name: argus-controller
  namespace: argus
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: argus
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: argus
  ports:
    - name: grpc
      port: 8444
      targetPort: 8444
    - name: metrics
      port: 9090
      targetPort: 9090
